if(NOT DEFINED AST_DISTANCE OR NOT DEFINED TEST_DIR)
    message(FATAL_ERROR "AST_DISTANCE and TEST_DIR are required")
endif()
file(MAKE_DIRECTORY "${TEST_DIR}/source" "${TEST_DIR}/target")
file(WRITE "${TEST_DIR}/source/Example.kt" "fun interface Example { fun pending(): Int }\nfun Example.Companion.Build(x: Int = 1): Int = x\nfun Build(x: Long = 1): Long = x\n")
file(WRITE "${TEST_DIR}/target/Example.cpp" "int Example::Build(int x) { return x; }\nlong Example::Build(long x) { return x; }\n")
execute_process(COMMAND "${AST_DISTANCE}" --compare-functions "${TEST_DIR}/source/Example.kt" kotlin "${TEST_DIR}/target/Example.cpp" cpp
    WORKING_DIRECTORY "${TEST_DIR}" OUTPUT_FILE "${TEST_DIR}/comparison.txt" ERROR_FILE "${TEST_DIR}/comparison.stderr" RESULT_VARIABLE status)
if(NOT status EQUAL 0)
    file(READ "${TEST_DIR}/comparison.stderr" error)
    message(FATAL_ERROR "Redirected comparison failed: ${status}: ${error}")
endif()
file(READ "${TEST_DIR}/comparison.txt" comparison)
if(NOT comparison MATCHES "Found 2 Kotlin functions" OR NOT comparison MATCHES "Found 2 C\\+\\+ functions" OR NOT comparison MATCHES "Strict matched pairs: 2 / 2")
    message(FATAL_ERROR "Wrong extraction/matching:\n${comparison}")
endif()
foreach(index RANGE 0 24)
    file(WRITE "${TEST_DIR}/target/Empty${index}.cpp" "// no implementation\n")
endforeach()
execute_process(COMMAND "${AST_DISTANCE}" --symbols-stubs "${TEST_DIR}/source" "${TEST_DIR}/target" --json
    WORKING_DIRECTORY "${TEST_DIR}" OUTPUT_VARIABLE json ERROR_VARIABLE diagnostics RESULT_VARIABLE status)
if(NOT status EQUAL 0)
    message(FATAL_ERROR "Captured JSON report failed: ${status}: ${diagnostics}")
endif()
file(WRITE "${TEST_DIR}/findings.json" "${json}")
string(JSON size LENGTH "${json}" findings)
if(NOT size EQUAL 25)
    message(FATAL_ERROR "Expected all 25 empty translation units, got ${size}: ${json}")
endif()
string(JSON category GET "${json}" classification)
if(NOT category STREQUAL "review_candidates_not_verified_stubs")
    message(FATAL_ERROR "Wrong classification: ${category}")
endif()
execute_process(COMMAND "${AST_DISTANCE}" --symbols-stubs "${TEST_DIR}/source" "${TEST_DIR}/target"
    WORKING_DIRECTORY "${TEST_DIR}" OUTPUT_VARIABLE human ERROR_VARIABLE diagnostics RESULT_VARIABLE status)
if(NOT status EQUAL 0 OR NOT human MATCHES "Empty24.cpp" OR human MATCHES "[.][.][.] and")
    message(FATAL_ERROR "Truncated/failed human report: ${status}: ${human}: ${diagnostics}")
endif()
execute_process(COMMAND "${AST_DISTANCE}" --compare-functions "${TEST_DIR}/source/missing.kt" kotlin "${TEST_DIR}/target/Example.cpp" cpp
    WORKING_DIRECTORY "${TEST_DIR}" OUTPUT_VARIABLE output ERROR_VARIABLE error RESULT_VARIABLE status)
if(status EQUAL 0 OR NOT error MATCHES "Cannot open source")
    message(FATAL_ERROR "Missing input was not rejected: ${status}: ${output}: ${error}")
endif()
message(STATUS "Redirected comparison, captured JSON, complete human report and input failure assertions passed")
