if(NOT DEFINED AST_DISTANCE OR NOT DEFINED TEST_DIR)
    message(FATAL_ERROR "AST_DISTANCE and TEST_DIR are required")
endif()
file(REMOVE_RECURSE "${TEST_DIR}")
file(MAKE_DIRECTORY "${TEST_DIR}/source" "${TEST_DIR}/target" "${TEST_DIR}/rust" "${TEST_DIR}/kotlin")
file(WRITE "${TEST_DIR}/source/Example.kt" "class Example {\n val count: Int = 1\n fun implemented(x: Int): Int = x\n fun declared(x: Int): Int = x\n fun missing(x: Int): Int = x\n}\nenum class Mode { START, STOP }\ntypealias Alias = Int\nconst val LIMIT: Int = 5\n")
file(WRITE "${TEST_DIR}/source/Absent.kt" "class Absent\n")
file(WRITE "${TEST_DIR}/target/Example.hpp" "// Transliterated from: Example.kt\nclass Example { public: int count = 1; int implemented(int x) { return x; } int declared(int x); };\nenum class Mode { START };\nusing Alias = int;\nconstexpr int LIMIT = 5;\n")
file(WRITE "${TEST_DIR}/target/Example.cpp" "// Implementation is inline in the companion header.\n#include \"Example.hpp\"\n")
execute_process(COMMAND "${AST_DISTANCE}" --deep "${TEST_DIR}/source" kotlin "${TEST_DIR}/target" cpp
    WORKING_DIRECTORY "${TEST_DIR}" OUTPUT_FILE "${TEST_DIR}/deep.txt" ERROR_FILE "${TEST_DIR}/deep.stderr" RESULT_VARIABLE status)
file(READ "${TEST_DIR}/deep.txt" report)
file(READ "${TEST_DIR}/deep.stderr" errors)
if(NOT status EQUAL 0)
    message(FATAL_ERROR "Deep comparison failed: ${status}: ${report}: ${errors}")
endif()
foreach(expected "MISSING_FILE Absent.kt" "MISSING_SYMBOL type Absent" "MISSING_SYMBOL function Example::missing" "DECLARATION_ONLY function Example::declared" "PRESENT property Example::count" "PRESENT property LIMIT" "PRESENT type_alias Alias" "MISSING_SYMBOL enum_variant Mode::STOP")
    string(FIND "${report}" "${expected}" found)
    if(found LESS 0)
        message(FATAL_ERROR "Missing inventory evidence ${expected}: ${report}")
    endif()
endforeach()
if(report MATCHES "missing types: Alias")
    message(FATAL_ERROR "Type alias falsely reported missing: ${report}")
endif()
if(report MATCHES "Example.*\\[STUB\\]")
    message(FATAL_ERROR "Inline companion implementation misclassified as stub: ${report}")
endif()
file(READ "${TEST_DIR}/deep_symbol_inventory.txt" saved)
if(NOT saved MATCHES "MISSING_SYMBOL function Example::missing")
    message(FATAL_ERROR "Deep inventory was not persisted")
endif()
execute_process(COMMAND "${AST_DISTANCE}" --deep "${TEST_DIR}/source/Example.kt" kotlin "${TEST_DIR}/target/Example.cpp" cpp
    WORKING_DIRECTORY "${TEST_DIR}" OUTPUT_VARIABLE single ERROR_VARIABLE errors RESULT_VARIABLE status)
if(NOT status EQUAL 0 OR NOT single MATCHES "PRESENT function Example::implemented" OR NOT single MATCHES "PRESENT property LIMIT")
    message(FATAL_ERROR "Single C++ file lost its companion header: ${status}: ${single}: ${errors}")
endif()
# Keep primary and supplementary totals wired in Rust -> Kotlin reporting.
file(WRITE "${TEST_DIR}/rust/example.rs" "pub struct Example {}\npub const LIMIT: i32 = 5;\npub type Alias = i32;\n")
file(WRITE "${TEST_DIR}/kotlin/Example.kt" "class Example\nconst val LIMIT: Int = 5\ntypealias Alias = Int\n")
execute_process(COMMAND "${AST_DISTANCE}" --symbol-parity "${TEST_DIR}/rust" "${TEST_DIR}/kotlin"
    WORKING_DIRECTORY "${TEST_DIR}" OUTPUT_VARIABLE parity ERROR_VARIABLE errors RESULT_VARIABLE status)
if(NOT status EQUAL 0 OR NOT parity MATCHES "Production symbols [(]all[)]: 3/3" OR NOT parity MATCHES "Test symbols [(]all[)]: +0/0")
    message(FATAL_ERROR "Rust/Kotlin combined totals regression: ${status}: ${parity}: ${errors}")
endif()
execute_process(COMMAND "${AST_DISTANCE}" --deep "${TEST_DIR}/does-not-exist" kotlin "${TEST_DIR}/target" cpp
    WORKING_DIRECTORY "${TEST_DIR}" OUTPUT_VARIABLE output ERROR_VARIABLE errors RESULT_VARIABLE status)
if(status EQUAL 0 OR NOT errors MATCHES "Cannot open codebase root")
    message(FATAL_ERROR "Missing root silently reported complete: ${status}: ${output}: ${errors}")
endif()
message(STATUS "Deep missing files/API/functions/properties/enum/alias inventory and Rust/Kotlin totals verified")
