file(REMOVE_RECURSE "${TEST_DIR}")
file(MAKE_DIRECTORY "${TEST_DIR}/source/alpha" "${TEST_DIR}/source/beta" "${TEST_DIR}/target")
file(WRITE "${TEST_DIR}/source/alpha/Example.kt" "package alpha.core\nfun nextValue(value: Int): Int = value + 1\n")
file(WRITE "${TEST_DIR}/source/beta/Example.kt" "package beta.core\nfun nextValue(value: Int): Int = value + 1\n")
function(compare label source target expected)
    execute_process(COMMAND "${AST_DISTANCE}" --compare-functions "${source}" kotlin "${target}" cpp
        WORKING_DIRECTORY "${TEST_DIR}" RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE errors)
    file(WRITE "${TEST_DIR}/${label}.txt" "${output}\n${errors}")
    if(expected STREQUAL "pass")
        if(NOT status EQUAL 0 OR NOT output MATCHES "Strict matched pairs: 1 / 1")
            message(FATAL_ERROR "${label} unexpectedly failed: ${status}: ${output}: ${errors}")
        endif()
    elseif(status EQUAL 0 OR NOT errors MATCHES "${expected}")
        message(FATAL_ERROR "${label} failed to reject identity: ${status}: ${output}: ${errors}")
    endif()
endfunction()
file(WRITE "${TEST_DIR}/target/Example.cpp" "// Transliterated from: alpha/Example.kt\nnamespace beta::core { int next_value(int value) { return value + 1; } }\n")
compare(namespace_wrong "${TEST_DIR}/source/alpha/Example.kt" "${TEST_DIR}/target/Example.cpp" "Namespace/package mismatch")
execute_process(COMMAND "${AST_DISTANCE}" --translit-distance "${TEST_DIR}/source/alpha/Example.kt" kotlin "${TEST_DIR}/target/Example.cpp" cpp
    WORKING_DIRECTORY "${TEST_DIR}" RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE errors)
if(status EQUAL 0 OR NOT errors MATCHES "Namespace/package mismatch")
    message(FATAL_ERROR "Emitted comparison ignored identity: ${status}: ${output}: ${errors}")
endif()
compare(provenance_wrong "${TEST_DIR}/source/beta/Example.kt" "${TEST_DIR}/target/Example.cpp" "Provenance mismatch")
execute_process(COMMAND "${AST_DISTANCE}" --deep "${TEST_DIR}/source" kotlin "${TEST_DIR}/target" cpp
    WORKING_DIRECTORY "${TEST_DIR}" RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE errors)
if(NOT status EQUAL 0 OR NOT output MATCHES "IDENTITY_MISMATCH" OR NOT output MATCHES "MISSING_FILE alpha/Example.kt" OR NOT output MATCHES "MISSING_FILE beta/Example.kt")
    message(FATAL_ERROR "Deep contradictory marker rescued by filename: ${status}: ${output}: ${errors}")
endif()
file(WRITE "${TEST_DIR}/target/Example.cpp" "// Transliterated from: beta/Example.kt\nnamespace beta { namespace core { int next_value(int value) { return value + 1; } } }\n")
compare(classic_namespace "${TEST_DIR}/source/beta/Example.kt" "${TEST_DIR}/target/Example.cpp" "pass")
execute_process(COMMAND "${AST_DISTANCE}" --deep "${TEST_DIR}/source" kotlin "${TEST_DIR}/target" cpp
    WORKING_DIRECTORY "${TEST_DIR}" RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE errors)
file(WRITE "${TEST_DIR}/correct-deep.txt" "${output}\n${errors}")
if(NOT status EQUAL 0 OR NOT output MATCHES "MISSING_FILE alpha/Example.kt" OR output MATCHES "MISSING_FILE beta/Example.kt" OR NOT output MATCHES "AST Emitted Transliteration Distance")
    message(FATAL_ERROR "Deep correct same basename pair failed: ${status}: ${output}: ${errors}")
endif()
file(READ "${TEST_DIR}/deep_transliteration_evidence.txt" evidence)
if(NOT evidence MATCHES "span_rule_coverage: 1.000000" OR NOT evidence MATCHES "namespace beta::core" OR NOT evidence MATCHES "Ordered logic sequences are equal")
    message(FATAL_ERROR "Deep emitted evidence missing: ${evidence}")
endif()
file(WRITE "${TEST_DIR}/target/Example.cpp" "/** Transliterated from: beta/Example.kt:2-2 */\nnamespace beta::core { int next_value(int value) { return value + 1; } }\n")
compare(line_range_provenance "${TEST_DIR}/source/beta/Example.kt" "${TEST_DIR}/target/Example.cpp" "pass")
file(WRITE "${TEST_DIR}/target/Example.cpp" "// Transliterated from: ${TEST_DIR}/source/beta/Example.kt\nnamespace beta::core { int next_value(int value) { return value + 1; } }\n")
compare(absolute_provenance "${TEST_DIR}/source/beta/Example.kt" "${TEST_DIR}/target/Example.cpp" "pass")
# Empty scopes cannot claim an implementation in an unrelated namespace.
file(WRITE "${TEST_DIR}/target/Example.cpp" "namespace beta::core {} namespace alpha::core { int next_value(int value) { return value + 1; } }\n")
compare(empty_scope_claim "${TEST_DIR}/source/beta/Example.kt" "${TEST_DIR}/target/Example.cpp" "Namespace/package mismatch")
file(WRITE "${TEST_DIR}/target/Example.cpp" "namespace helper {} namespace beta::core { int next_value(int value) { return value + 1; } }\n")
compare(empty_helper_scope "${TEST_DIR}/source/beta/Example.kt" "${TEST_DIR}/target/Example.cpp" "pass")
file(WRITE "${TEST_DIR}/target/Example.cpp" "namespace unrelated { int helper() { return 1; } } namespace beta::core { int next_value(int value) { return value + 1; } }\n")
compare(mixed_sibling_scopes "${TEST_DIR}/source/beta/Example.kt" "${TEST_DIR}/target/Example.cpp" "Identity conflict")
file(WRITE "${TEST_DIR}/target/Example.cpp" "namespace clang { class ASTContext; class FunctionDecl; }\nnamespace beta::core { int next_value(int value) { return value + 1; } }\n")
compare(foreign_forward_types "${TEST_DIR}/source/beta/Example.kt" "${TEST_DIR}/target/Example.cpp" "pass")
file(WRITE "${TEST_DIR}/target/Example.cpp" "class External;\nnamespace beta::core { int next_value(int value) { return value + 1; } }\n")
compare(global_forward_type "${TEST_DIR}/source/beta/Example.kt" "${TEST_DIR}/target/Example.cpp" "pass")
file(WRITE "${TEST_DIR}/target/Example.cpp" "namespace unrelated { class ActualType {}; }\nnamespace beta::core { int next_value(int value) { return value + 1; } }\n")
compare(foreign_type_definition "${TEST_DIR}/source/beta/Example.kt" "${TEST_DIR}/target/Example.cpp" "Identity conflict")
# A missing marker may use an exact basename only with the declared namespace.
file(WRITE "${TEST_DIR}/target/Example.cpp" "namespace beta::core { int next_value(int value) { return value + 1; } }\n")
execute_process(COMMAND "${AST_DISTANCE}" --deep "${TEST_DIR}/source" kotlin "${TEST_DIR}/target" cpp
    WORKING_DIRECTORY "${TEST_DIR}" RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE errors)
if(NOT status EQUAL 0 OR NOT output MATCHES "MISSING_FILE alpha/Example.kt" OR output MATCHES "MISSING_FILE beta/Example.kt")
    message(FATAL_ERROR "Filename fallback crossed namespace: ${output}: ${errors}")
endif()
# Namespace spelling/case and component boundaries carry identity.
foreach(package IN ITEMS betaCore beta.co_re Beta.core beta.Core be.ta.core)
    string(REPLACE "." "::" cpp_namespace "${package}")
    file(WRITE "${TEST_DIR}/target/Example.cpp" "namespace ${cpp_namespace} { int next_value(int value) { return value + 1; } }\n")
    compare("distinct_${package}" "${TEST_DIR}/source/beta/Example.kt" "${TEST_DIR}/target/Example.cpp" "Namespace/package mismatch")
endforeach()
file(WRITE "${TEST_DIR}/target/Example.hpp" "// Transliterated from: beta/Example.kt\nnamespace beta::core { int next_value(int); }\n")
file(WRITE "${TEST_DIR}/target/Example.cpp" "#include \"Example.hpp\"\nnamespace alpha::core { int next_value(int value) { return value + 1; } }\n")
compare(companion_namespace "${TEST_DIR}/source/beta/Example.kt" "${TEST_DIR}/target/Example.cpp" "Identity conflict")
file(WRITE "${TEST_DIR}/target/Example.cpp" "// Transliterated from: alpha/Example.kt\nnamespace beta::core { int next_value(int value) { return value + 1; } }\n")
compare(companion_provenance "${TEST_DIR}/source/beta/Example.kt" "${TEST_DIR}/target/Example.cpp" "Identity conflict")
# Include-only implementation files may inherit the companion header identity.
file(WRITE "${TEST_DIR}/target/Example.hpp" "// Transliterated from: beta/Example.kt\nnamespace beta::core { inline int next_value(int value) { return value + 1; } }\n")
file(WRITE "${TEST_DIR}/target/Example.cpp" "#include \"Example.hpp\"\n")
execute_process(COMMAND "${AST_DISTANCE}" --deep "${TEST_DIR}/source" kotlin "${TEST_DIR}/target" cpp
    WORKING_DIRECTORY "${TEST_DIR}" RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE errors)
if(NOT status EQUAL 0 OR output MATCHES "MISSING_FILE beta/Example.kt" OR NOT output MATCHES "PRESENT function nextValue")
    message(FATAL_ERROR "Header identity/implementation lost: ${output}: ${errors}")
endif()
# Empty classic companion namespace chains retain their terminal namespace.
file(WRITE "${TEST_DIR}/target/Example.cpp" "#include \"Example.hpp\"\nnamespace beta { namespace core {} }\n")
compare(empty_nested_companion "${TEST_DIR}/source/beta/Example.kt" "${TEST_DIR}/target/Example.hpp" "pass")
execute_process(COMMAND "${AST_DISTANCE}" --deep "${TEST_DIR}/source" kotlin "${TEST_DIR}/target" cpp
    WORKING_DIRECTORY "${TEST_DIR}" RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE errors)
if(NOT status EQUAL 0 OR output MATCHES "MISSING_FILE beta/Example.kt" OR output MATCHES "Companion namespace conflict")
    message(FATAL_ERROR "Empty classic companion namespace lost: ${output}: ${errors}")
endif()
# Short/full companion markers must both identify this exact actual source.
file(WRITE "${TEST_DIR}/target/Example.cpp" "// Transliterated from: beta/Example.kt\nnamespace beta { namespace core {} }\n")
file(WRITE "${TEST_DIR}/target/Example.hpp" "// Transliterated from: ${TEST_DIR}/source/beta/Example.kt\nnamespace beta::core { inline int next_value(int value) { return value + 1; } }\n")
compare(equivalent_companion_provenance "${TEST_DIR}/source/beta/Example.kt" "${TEST_DIR}/target/Example.hpp" "pass")
execute_process(COMMAND "${AST_DISTANCE}" --compare-functions "${TEST_DIR}/target/Example.hpp" cpp "${TEST_DIR}/source/beta/Example.kt" kotlin
    WORKING_DIRECTORY "${TEST_DIR}" RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE errors)
if(NOT status EQUAL 0 OR NOT output MATCHES "Strict matched pairs: 1 / 1")
    message(FATAL_ERROR "Reverse comparison lost actual provenance: ${output}: ${errors}")
endif()
file(WRITE "${TEST_DIR}/target/Example.hpp" "// Transliterated from: invented/prefix/beta/Example.kt\nnamespace beta::core { inline int next_value(int value) { return value + 1; } }\n")
compare(fake_prefix_companion "${TEST_DIR}/source/beta/Example.kt" "${TEST_DIR}/target/Example.hpp" "Provenance mismatch")
execute_process(COMMAND "${AST_DISTANCE}" --compare-functions "${TEST_DIR}/target/Example.hpp" cpp "${TEST_DIR}/source/beta/Example.kt" kotlin
    WORKING_DIRECTORY "${TEST_DIR}" RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE errors)
if(status EQUAL 0 OR NOT errors MATCHES "Provenance mismatch")
    message(FATAL_ERROR "Reverse comparison accepted invented companion provenance: ${output}: ${errors}")
endif()
file(MAKE_DIRECTORY "${TEST_DIR}/ambiguous-source/one" "${TEST_DIR}/ambiguous-source/two" "${TEST_DIR}/ambiguous-target")
foreach(directory IN ITEMS one two)
    file(WRITE "${TEST_DIR}/ambiguous-source/${directory}/Example.kt" "package beta.core\nfun nextValue(value: Int): Int = value + 1\n")
endforeach()
file(WRITE "${TEST_DIR}/ambiguous-target/Example.cpp" "namespace beta::core { int next_value(int value) { return value + 1; } }\n")
execute_process(COMMAND "${AST_DISTANCE}" --deep "${TEST_DIR}/ambiguous-source" kotlin "${TEST_DIR}/ambiguous-target" cpp
    WORKING_DIRECTORY "${TEST_DIR}" RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE errors)
if(NOT status EQUAL 0 OR NOT output MATCHES "Ambiguous filename/namespace pairing requires provenance" OR NOT output MATCHES "MISSING_FILE one/Example.kt" OR NOT output MATCHES "MISSING_FILE two/Example.kt")
    message(FATAL_ERROR "Equal source-set candidates arbitrarily paired: ${output}: ${errors}")
endif()
# A bare root filename and full marker may agree only against the actual source.
file(WRITE "${TEST_DIR}/target/Example.hpp" "// Transliterated from: ${TEST_DIR}/source/beta/Example.kt\nnamespace beta::core { inline int next_value(int value) { return value + 1; } }\n")
file(WRITE "${TEST_DIR}/target/Example.cpp" "// Transliterated from: Example.kt\nnamespace beta { namespace core {} }\n")
compare(bare_full_provenance "${TEST_DIR}/source/beta/Example.kt" "${TEST_DIR}/target/Example.hpp" "pass")
file(WRITE "${TEST_DIR}/target/Example.hpp" "// Transliterated from: invented/prefix/Example.kt\nnamespace beta::core { inline int next_value(int value) { return value + 1; } }\n")
compare(bare_fake_prefix "${TEST_DIR}/source/beta/Example.kt" "${TEST_DIR}/target/Example.hpp" "Provenance mismatch")
# Generic extension lowering needs an explicit receiver, not a namesake.
file(MAKE_DIRECTORY "${TEST_DIR}/extension-source" "${TEST_DIR}/extension-target")
file(WRITE "${TEST_DIR}/extension-source/Generic.kt" "package beta.core\nfun <T> Flow<T>.drop(count: Int): Flow<T> = this\n")
file(WRITE "${TEST_DIR}/extension-target/Generic.hpp" "// Transliterated from: Generic.kt\nnamespace beta::core { template<class T> Flow<T> drop(Flow<T> upstream, int count) { return upstream; } }\n")
file(WRITE "${TEST_DIR}/extension-target/Generic.cpp" "namespace beta { namespace core {} }\n")
execute_process(COMMAND "${AST_DISTANCE}" --compare-functions "${TEST_DIR}/extension-source/Generic.kt" kotlin "${TEST_DIR}/extension-target/Generic.hpp" cpp
    WORKING_DIRECTORY "${TEST_DIR}" RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE errors)
file(WRITE "${TEST_DIR}/extension-receiver.txt" "${output}\n${errors}")
if(NOT status EQUAL 0 OR NOT output MATCHES "Strict matched pairs: 1 / 1")
    message(FATAL_ERROR "Generic extension receiver not matched: ${output}: ${errors}")
endif()
file(WRITE "${TEST_DIR}/extension-target/Generic.hpp" "// Transliterated from: Generic.kt\nnamespace beta::core { int drop(int count) { return count; } }\n")
execute_process(COMMAND "${AST_DISTANCE}" --compare-functions "${TEST_DIR}/extension-source/Generic.kt" kotlin "${TEST_DIR}/extension-target/Generic.hpp" cpp
    WORKING_DIRECTORY "${TEST_DIR}" RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE errors)
if(NOT status EQUAL 0 OR NOT output MATCHES "Strict matched pairs: 0 / 1")
    message(FATAL_ERROR "Namesake accepted without extension receiver: ${output}: ${errors}")
endif()
# Local collectors in separate operators cannot pair by copied method bodies.
file(MAKE_DIRECTORY "${TEST_DIR}/local-source" "${TEST_DIR}/local-target")
file(WRITE "${TEST_DIR}/local-source/Local.kt" "package beta.core\nfun collectWhile() { val collector = object { fun emit(value: Int) { predicate(value) } }; collect(collector) }\n")
file(WRITE "${TEST_DIR}/local-target/Local.hpp" "// Transliterated from: Local.kt\nnamespace beta::core { void drop() { class Wrong { void emit(int value) { predicate(value); } }; } void collect_while() { class Correct { void emit(int value) { changed(value); } }; } }\n")
execute_process(COMMAND "${AST_DISTANCE}" --compare-functions "${TEST_DIR}/local-source/Local.kt" kotlin "${TEST_DIR}/local-target/Local.hpp" cpp
    WORKING_DIRECTORY "${TEST_DIR}" RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE errors)
file(WRITE "${TEST_DIR}/local-owner.report.txt" "${output}\n${errors}")
if(NOT status EQUAL 0 OR NOT output MATCHES "emit:2 -> beta::core::Correct::emit:2" OR output MATCHES "emit:2 -> beta::core::Wrong::emit:2")
    message(FATAL_ERROR "Wrong enclosing callable paired local method: ${output}: ${errors}")
endif()
execute_process(COMMAND "${AST_DISTANCE}" --compare-functions "${TEST_DIR}/local-target/Local.hpp" cpp "${TEST_DIR}/local-source/Local.kt" kotlin
    WORKING_DIRECTORY "${TEST_DIR}" RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE errors)
file(WRITE "${TEST_DIR}/local-owner.reverse-report.txt" "${output}\n${errors}")
if(NOT status EQUAL 0 OR NOT output MATCHES "Strict matched pairs: 2 / 4" OR output MATCHES "Wrong::emit:2 -> emit:2")
    message(FATAL_ERROR "Reverse local callable pairing lost owner evidence: ${output}: ${errors}")
endif()

file(WRITE "${TEST_DIR}/local-source/Macro.kt" "package beta.core\nfun invokeSuspend() { emit(value) }\n")
file(WRITE "${TEST_DIR}/local-target/Macro.hpp" [=[// Transliterated from: Macro.kt
namespace beta::core {
void* invoke_suspend() {
  coroutine_begin(this)
  coroutine_yield(this, emit(value, this));
  coroutine_end(this)
  }
void release_intercepted() { release(); }
}
]=])
execute_process(COMMAND "${AST_DISTANCE}" --compare-functions "${TEST_DIR}/local-source/Macro.kt" kotlin "${TEST_DIR}/local-target/Macro.hpp" cpp
    WORKING_DIRECTORY "${TEST_DIR}" RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE errors)
file(WRITE "${TEST_DIR}/macro.report.txt" "${output}\n${errors}")
if(NOT status EQUAL 0 OR NOT output MATCHES "Strict matched pairs: 1 / 1" OR errors MATCHES "has parser errors" OR
    NOT errors MATCHES "parsed coroutine statement macro with offset-preserving terminator adapter; expansion remains unverified")
    message(FATAL_ERROR "Statement macro adaptation was incomplete or undisclosed: ${output}: ${errors}")
endif()
message(STATUS "Namespace/provenance and lexical callable identity, bounded statement macros, duplicates, companion conflicts, and full deep emission verified")

# Runtime-class overloads cannot be credited to receiver-only template overloads.
file(MAKE_DIRECTORY "${TEST_DIR}/overload-source" "${TEST_DIR}/overload-target")
file(WRITE "${TEST_DIR}/overload-source/Reflection.kt" "package beta.core\ninline fun <reified R> Flow<Any>.filterIsInstance(): Flow<R> = this\nfun <R> Flow<Any>.filterIsInstance(klass: KClass<R>): Flow<R> = this\n")
file(WRITE "${TEST_DIR}/overload-target/Reflection.hpp" "// Transliterated from: Reflection.kt\nnamespace beta::core { template<class R, class T> Flow<R> filter_is_instance(Flow<T> upstream) { return upstream; } template<class R, class T> Flow<R> filter_is_instance(std::shared_ptr<Flow<T>> upstream) { return *upstream; } }\n")
execute_process(COMMAND "${AST_DISTANCE}" --compare-functions "${TEST_DIR}/overload-source/Reflection.kt" kotlin "${TEST_DIR}/overload-target/Reflection.hpp" cpp
    WORKING_DIRECTORY "${TEST_DIR}" RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE errors)
file(WRITE "${TEST_DIR}/missing-runtime-class.txt" "${output}\n${errors}")
if(NOT status EQUAL 0 OR NOT output MATCHES "Strict matched pairs: 1 / 2" OR NOT output MATCHES "unmatched source: 1" OR NOT output MATCHES "klass: KClass")
    message(FATAL_ERROR "Receiver-only overloads hid runtime-class parameter: ${output}: ${errors}")
endif()
file(WRITE "${TEST_DIR}/overload-target/Reflection.hpp" "// Transliterated from: Reflection.kt\nnamespace beta::core { template<class R, class T> Flow<R> filter_is_instance(Flow<T> upstream) { return upstream; } template<class R, class T> Flow<R> filter_is_instance(Flow<T> upstream, KClass<R> klass) { return upstream; } }\n")
execute_process(COMMAND "${AST_DISTANCE}" --compare-functions "${TEST_DIR}/overload-source/Reflection.kt" kotlin "${TEST_DIR}/overload-target/Reflection.hpp" cpp
    WORKING_DIRECTORY "${TEST_DIR}" RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE errors)
file(WRITE "${TEST_DIR}/present-runtime-class.txt" "${output}\n${errors}")
if(NOT status EQUAL 0 OR NOT output MATCHES "Strict matched pairs: 2 / 2")
    message(FATAL_ERROR "Genuine runtime-class overload was rejected: ${output}: ${errors}")
endif()
