file(REMOVE_RECURSE "${TEST_DIR}")
file(MAKE_DIRECTORY "${TEST_DIR}/source/alpha" "${TEST_DIR}/source/beta" "${TEST_DIR}/target")
file(WRITE "${TEST_DIR}/source/alpha/Example.kt" "package alpha.core\nfun nextValue(value: Int): Int = value + 1\n")
file(WRITE "${TEST_DIR}/source/beta/Example.kt" "package beta.core\nfun nextValue(value: Int): Int = value + 1\n")
function(compare label source target expected)
    execute_process(COMMAND "${AST_DISTANCE}" --compare-functions "${source}" kotlin "${target}" cpp
        WORKING_DIRECTORY "${TEST_DIR}" RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE errors)
    file(WRITE "${TEST_DIR}/${label}.txt" "${output}\n${errors}")
    if(expected STREQUAL "pass")
        if(NOT status EQUAL 0 OR NOT output MATCHES "Strict matched pairs: 1 / 1")
            message(FATAL_ERROR "${label} unexpectedly failed: ${status}: ${output}: ${errors}")
        endif()
    elseif(status EQUAL 0 OR NOT errors MATCHES "${expected}")
        message(FATAL_ERROR "${label} failed to reject identity: ${status}: ${output}: ${errors}")
    endif()
endfunction()
file(WRITE "${TEST_DIR}/target/Example.cpp" "// Transliterated from: alpha/Example.kt\nnamespace beta::core { int next_value(int value) { return value + 1; } }\n")
compare(namespace_wrong "${TEST_DIR}/source/alpha/Example.kt" "${TEST_DIR}/target/Example.cpp" "Namespace/package mismatch")
execute_process(COMMAND "${AST_DISTANCE}" --translit-distance "${TEST_DIR}/source/alpha/Example.kt" kotlin "${TEST_DIR}/target/Example.cpp" cpp
    WORKING_DIRECTORY "${TEST_DIR}" RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE errors)
if(status EQUAL 0 OR NOT errors MATCHES "Namespace/package mismatch")
    message(FATAL_ERROR "Emitted comparison ignored identity: ${status}: ${output}: ${errors}")
endif()
compare(provenance_wrong "${TEST_DIR}/source/beta/Example.kt" "${TEST_DIR}/target/Example.cpp" "Provenance mismatch")
execute_process(COMMAND "${AST_DISTANCE}" --deep "${TEST_DIR}/source" kotlin "${TEST_DIR}/target" cpp
    WORKING_DIRECTORY "${TEST_DIR}" RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE errors)
if(NOT status EQUAL 0 OR NOT output MATCHES "IDENTITY_MISMATCH" OR NOT output MATCHES "MISSING_FILE alpha/Example.kt" OR NOT output MATCHES "MISSING_FILE beta/Example.kt")
    message(FATAL_ERROR "Deep contradictory marker rescued by filename: ${status}: ${output}: ${errors}")
endif()
file(WRITE "${TEST_DIR}/target/Example.cpp" "// Transliterated from: beta/Example.kt\nnamespace beta { namespace core { int next_value(int value) { return value + 1; } } }\n")
compare(classic_namespace "${TEST_DIR}/source/beta/Example.kt" "${TEST_DIR}/target/Example.cpp" "pass")
execute_process(COMMAND "${AST_DISTANCE}" --deep "${TEST_DIR}/source" kotlin "${TEST_DIR}/target" cpp
    WORKING_DIRECTORY "${TEST_DIR}" RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE errors)
file(WRITE "${TEST_DIR}/correct-deep.txt" "${output}\n${errors}")
if(NOT status EQUAL 0 OR NOT output MATCHES "MISSING_FILE alpha/Example.kt" OR output MATCHES "MISSING_FILE beta/Example.kt" OR NOT output MATCHES "AST Emitted Transliteration Distance")
    message(FATAL_ERROR "Deep correct same basename pair failed: ${status}: ${output}: ${errors}")
endif()
file(READ "${TEST_DIR}/deep_transliteration_evidence.txt" evidence)
if(NOT evidence MATCHES "span_rule_coverage: 1.000000" OR NOT evidence MATCHES "namespace beta::core" OR NOT evidence MATCHES "Ordered logic sequences are equal")
    message(FATAL_ERROR "Deep emitted evidence missing: ${evidence}")
endif()
file(WRITE "${TEST_DIR}/target/Example.cpp" "/** Transliterated from: beta/Example.kt:2-2 */\nnamespace beta::core { int next_value(int value) { return value + 1; } }\n")
compare(line_range_provenance "${TEST_DIR}/source/beta/Example.kt" "${TEST_DIR}/target/Example.cpp" "pass")
file(WRITE "${TEST_DIR}/target/Example.cpp" "// Transliterated from: ${TEST_DIR}/source/beta/Example.kt\nnamespace beta::core { int next_value(int value) { return value + 1; } }\n")
compare(absolute_provenance "${TEST_DIR}/source/beta/Example.kt" "${TEST_DIR}/target/Example.cpp" "pass")
# Empty scopes cannot claim an implementation in an unrelated namespace.
file(WRITE "${TEST_DIR}/target/Example.cpp" "namespace beta::core {} namespace alpha::core { int next_value(int value) { return value + 1; } }\n")
compare(empty_scope_claim "${TEST_DIR}/source/beta/Example.kt" "${TEST_DIR}/target/Example.cpp" "Namespace/package mismatch")
file(WRITE "${TEST_DIR}/target/Example.cpp" "namespace helper {} namespace beta::core { int next_value(int value) { return value + 1; } }\n")
compare(empty_helper_scope "${TEST_DIR}/source/beta/Example.kt" "${TEST_DIR}/target/Example.cpp" "pass")
file(WRITE "${TEST_DIR}/target/Example.cpp" "namespace unrelated { int helper() { return 1; } } namespace beta::core { int next_value(int value) { return value + 1; } }\n")
compare(mixed_sibling_scopes "${TEST_DIR}/source/beta/Example.kt" "${TEST_DIR}/target/Example.cpp" "Identity conflict")
# A missing marker may use an exact basename only with the declared namespace.
file(WRITE "${TEST_DIR}/target/Example.cpp" "namespace beta::core { int next_value(int value) { return value + 1; } }\n")
execute_process(COMMAND "${AST_DISTANCE}" --deep "${TEST_DIR}/source" kotlin "${TEST_DIR}/target" cpp
    WORKING_DIRECTORY "${TEST_DIR}" RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE errors)
if(NOT status EQUAL 0 OR NOT output MATCHES "MISSING_FILE alpha/Example.kt" OR output MATCHES "MISSING_FILE beta/Example.kt")
    message(FATAL_ERROR "Filename fallback crossed namespace: ${output}: ${errors}")
endif()
# Namespace spelling/case and component boundaries carry identity.
foreach(package IN ITEMS betaCore beta.co_re Beta.core beta.Core be.ta.core)
    string(REPLACE "." "::" cpp_namespace "${package}")
    file(WRITE "${TEST_DIR}/target/Example.cpp" "namespace ${cpp_namespace} { int next_value(int value) { return value + 1; } }\n")
    compare("distinct_${package}" "${TEST_DIR}/source/beta/Example.kt" "${TEST_DIR}/target/Example.cpp" "Namespace/package mismatch")
endforeach()
file(WRITE "${TEST_DIR}/target/Example.hpp" "// Transliterated from: beta/Example.kt\nnamespace beta::core { int next_value(int); }\n")
file(WRITE "${TEST_DIR}/target/Example.cpp" "#include \"Example.hpp\"\nnamespace alpha::core { int next_value(int value) { return value + 1; } }\n")
compare(companion_namespace "${TEST_DIR}/source/beta/Example.kt" "${TEST_DIR}/target/Example.cpp" "Identity conflict")
file(WRITE "${TEST_DIR}/target/Example.cpp" "// Transliterated from: alpha/Example.kt\nnamespace beta::core { int next_value(int value) { return value + 1; } }\n")
compare(companion_provenance "${TEST_DIR}/source/beta/Example.kt" "${TEST_DIR}/target/Example.cpp" "Identity conflict")
# Include-only implementation files may inherit the companion header identity.
file(WRITE "${TEST_DIR}/target/Example.hpp" "// Transliterated from: beta/Example.kt\nnamespace beta::core { inline int next_value(int value) { return value + 1; } }\n")
file(WRITE "${TEST_DIR}/target/Example.cpp" "#include \"Example.hpp\"\n")
execute_process(COMMAND "${AST_DISTANCE}" --deep "${TEST_DIR}/source" kotlin "${TEST_DIR}/target" cpp
    WORKING_DIRECTORY "${TEST_DIR}" RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE errors)
if(NOT status EQUAL 0 OR output MATCHES "MISSING_FILE beta/Example.kt" OR NOT output MATCHES "PRESENT function nextValue")
    message(FATAL_ERROR "Header identity/implementation lost: ${output}: ${errors}")
endif()
file(MAKE_DIRECTORY "${TEST_DIR}/ambiguous-source/one" "${TEST_DIR}/ambiguous-source/two" "${TEST_DIR}/ambiguous-target")
foreach(directory IN ITEMS one two)
    file(WRITE "${TEST_DIR}/ambiguous-source/${directory}/Example.kt" "package beta.core\nfun nextValue(value: Int): Int = value + 1\n")
endforeach()
file(WRITE "${TEST_DIR}/ambiguous-target/Example.cpp" "namespace beta::core { int next_value(int value) { return value + 1; } }\n")
execute_process(COMMAND "${AST_DISTANCE}" --deep "${TEST_DIR}/ambiguous-source" kotlin "${TEST_DIR}/ambiguous-target" cpp
    WORKING_DIRECTORY "${TEST_DIR}" RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE errors)
if(NOT status EQUAL 0 OR NOT output MATCHES "Ambiguous filename/namespace pairing requires provenance" OR NOT output MATCHES "MISSING_FILE one/Example.kt" OR NOT output MATCHES "MISSING_FILE two/Example.kt")
    message(FATAL_ERROR "Equal source-set candidates arbitrarily paired: ${output}: ${errors}")
endif()
message(STATUS "Namespace/provenance identity, duplicates, companion conflicts, and full deep emission verified")
