file(MAKE_DIRECTORY "${TEST_DIR}")
file(WRITE "${TEST_DIR}/source.kt" [=[fun compareValue(inputValue: Int, limitValue: Int): Int { if (inputValue > limitValue) { return inputValue + 50 } else { return limitValue - 1 } }
]=])
set(faithful [=[int compare_value(int input_value, int limit_value) { if (input_value > limit_value) { return input_value + 50; } else { return limit_value - 1; } }
]=])
function(run_comparison text label)
    file(WRITE "${TEST_DIR}/${label}.cpp" "${text}")
    execute_process(COMMAND "${AST_DISTANCE}" --compare-functions "${TEST_DIR}/source.kt" kotlin "${TEST_DIR}/${label}.cpp" cpp
        WORKING_DIRECTORY "${TEST_DIR}" RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE error)
    file(WRITE "${TEST_DIR}/${label}.report.txt" "${output}\n${error}")
    if(NOT status EQUAL 0 OR NOT output MATCHES "Strict matched pairs: 1 / 1" OR NOT output MATCHES "NormalizedLogic")
        message(FATAL_ERROR "Failed ${label}: ${status}: ${output}: ${error}")
    endif()
    string(REGEX MATCH "Function body score [(]missing source functions count as 0[)]: ([0-9.]+)" found "${output}")
    if(NOT found)
        message(FATAL_ERROR "No body score in ${label}: ${output}")
    endif()
    set("${label}_score" "${CMAKE_MATCH_1}" PARENT_SCOPE)
endfunction()
run_comparison("${faithful}" faithful)
string(REPLACE "> limit_value" "< limit_value" reversed "${faithful}")
run_comparison("${reversed}" reversed)
string(REPLACE "50" "500" constant "${faithful}")
run_comparison("${constant}" constant)
string(REPLACE "int input_value" "double input_value" parameter "${faithful}")
run_comparison("${parameter}" parameter)
if(NOT reversed_score STRLESS faithful_score OR NOT constant_score STRLESS faithful_score OR NOT parameter_score STRLESS faithful_score)
    message(FATAL_ERROR "Drift failed: faithful=${faithful_score} reversed=${reversed_score} constant=${constant_score} parameter=${parameter_score}")
endif()
set(comments "// inputValue limitValue compareValue if return else 50 1\n${faithful}\n/* inputValue limitValue */")
run_comparison("${comments}" comments)
if(NOT comments_score STREQUAL faithful_score)
    message(FATAL_ERROR "Comments altered body metric: faithful=${faithful_score} comments=${comments_score}")
endif()
set(stuffed [=[// inputValue limitValue compareValue return if else next add remove
int compare_value(int input_value, int limit_value) { int copied_input = input_value; int copied_limit = limit_value; int copied_more = input_value + 50; int copied_less = limit_value - 1; const char* words = "inputValue limitValue if return else 50"; return 0; }
]=])
run_comparison("${stuffed}" stuffed)
if(NOT stuffed_score STRLESS "0.850" OR NOT stuffed_score STRLESS faithful_score)
    message(FATAL_ERROR "Vocabulary stuffing rescued fake: stuffed=${stuffed_score} faithful=${faithful_score}")
endif()
message(STATUS "Captured CLI drift: faithful=${faithful_score} reversed=${reversed_score} constant=${constant_score} parameter=${parameter_score}")
file(WRITE "${TEST_DIR}/source.kt" "fun update(x: Int): Int { return ++x }\n")
run_comparison("int update(int x) { return ++x; }" prefix_update)
run_comparison("int update(int x) { return --x; }" decrement_drift)
run_comparison("int update(int x) { return x++; }" postfix_drift)
run_comparison("int update(int x) { return x; }" omitted_update)
if(NOT decrement_drift_score STRLESS prefix_update_score OR NOT postfix_drift_score STRLESS prefix_update_score OR NOT omitted_update_score STRLESS prefix_update_score)
    message(FATAL_ERROR "Update operation drift was hidden: faithful=${prefix_update_score} decrement=${decrement_drift_score} postfix=${postfix_drift_score} omitted=${omitted_update_score}")
endif()
