// port-lint: source core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt
// Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:8-371
#pragma once
#include "CallableId.hpp"
namespace org::jetbrains::kotlin::name {
// Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:8-342
// NOTE(port): Scalar object properties use retained getters; C++ keyword
// collisions use _name suffixes. JVM object/field metadata is not supplied.
class StandardClassIds final {
public:
    // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:9-9
    static const FqName& base_kotlin_package();
    // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:10-10
    static const FqName& base_reflect_package();
    // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:11-11
    static const FqName& base_experimental_package();
    // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:12-12
    static const FqName& base_collections_package();
    // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:13-13
    static const FqName& base_sequences_package();
    // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:14-14
    static const FqName& base_ranges_package();
    // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:15-15
    static const FqName& base_jvm_package();
    // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:16-16
    static const FqName& base_js_package();
    // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:17-17
    static const FqName& base_annotations_jvm_package();
    // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:18-18
    static const FqName& base_jvm_internal_package();
    // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:19-19
    static const FqName& base_jvm_functions_package();
    // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:20-20
    static const FqName& base_annotation_package();
    // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:21-21
    static const FqName& base_internal_package();
    // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:22-22
    static const FqName& base_internal_ir_package();
    // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:23-23
    static const FqName& base_coroutines_package();
    // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:24-24
    static const FqName& base_coroutines_intrinsics_package();
    // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:25-25
    static const FqName& base_enums_package();
    // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:26-26
    static const FqName& base_contracts_package();
    // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:27-27
    static const FqName& base_concurrent_package();
    // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:28-28
    static const FqName& base_concurrent_atomics_package();
    // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:29-29
    static const FqName& base_test_package();
    // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:30-30
    static const FqName& base_text_package();
    // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:50-50
    static const ClassId& nothing();
    // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:51-51
    static const ClassId& unit();
    // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:52-52
    static const ClassId& any();
    // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:53-53
    static const ClassId& non_error();
    // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:54-54
    static const ClassId& rich_error();
    // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:55-55
    static const ClassId& enum_name();
    // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:56-56
    static const ClassId& annotation();
    // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:57-57
    static const ClassId& array();
    // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:59-59
    static const ClassId& boolean();
    // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:60-60
    static const ClassId& char_name();
    // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:61-61
    static const ClassId& byte();
    // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:62-62
    static const ClassId& short_name();
    // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:63-63
    static const ClassId& int_name();
    // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:64-64
    static const ClassId& long_name();
    // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:65-65
    static const ClassId& float_name();
    // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:66-66
    static const ClassId& double_name();
    // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:68-68
    static const ClassId& u_byte();
    // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:69-69
    static const ClassId& u_short();
    // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:70-70
    static const ClassId& u_int();
    // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:71-71
    static const ClassId& u_long();
    // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:73-73
    static const ClassId& char_sequence();
    // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:74-74
    static const ClassId& string();
    // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:75-75
    static const ClassId& throwable();
    // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:77-77
    static const ClassId& cloneable();
    // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:79-79
    static const ClassId& k_property();
    // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:80-80
    static const ClassId& k_mutable_property();
    // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:81-81
    static const ClassId& k_property0();
    // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:82-82
    static const ClassId& k_mutable_property0();
    // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:83-83
    static const ClassId& k_property1();
    // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:84-84
    static const ClassId& k_mutable_property1();
    // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:85-85
    static const ClassId& k_property2();
    // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:86-86
    static const ClassId& k_mutable_property2();
    // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:87-87
    static const ClassId& k_function();
    // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:88-88
    static const ClassId& k_class();
    // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:89-89
    static const ClassId& k_callable();
    // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:90-90
    static const ClassId& k_type();
    // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:92-92
    static const ClassId& sequence();
    // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:94-94
    static const ClassId& comparable();
    // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:95-95
    static const ClassId& number();
    // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:97-97
    static const ClassId& function();
    // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:98-98
    static const ClassId& suspend_function();
    // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:116-116
    static const ClassId& continuation();
    // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:117-117
    static const ClassId& coroutine_context();
    // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:139-139
    static const ClassId& iterator();
    // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:140-140
    static const ClassId& iterable();
    // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:141-141
    static const ClassId& collection();
    // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:142-142
    static const ClassId& list();
    // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:143-143
    static const ClassId& list_iterator();
    // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:144-144
    static const ClassId& set();
    // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:145-145
    static const ClassId& map();
    // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:146-146
    static const ClassId& abstract_map();
    // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:147-147
    static const ClassId& mutable_iterator();
    // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:148-148
    static const ClassId& char_iterator();
    // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:150-150
    static const ClassId& mutable_iterable();
    // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:151-151
    static const ClassId& mutable_collection();
    // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:152-152
    static const ClassId& mutable_list();
    // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:153-153
    static const ClassId& mutable_list_iterator();
    // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:154-154
    static const ClassId& mutable_set();
    // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:155-155
    static const ClassId& mutable_map();
    // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:157-157
    static const ClassId& map_entry();
    // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:158-158
    static const ClassId& mutable_map_entry();
    // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:160-160
    static const ClassId& result();
    // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:162-162
    static const ClassId& int_range();
    // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:163-163
    static const ClassId& long_range();
    // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:164-164
    static const ClassId& char_range();
    // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:166-166
    static const ClassId& annotation_retention();
    // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:167-167
    static const ClassId& annotation_target();
    // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:168-168
    static const ClassId& deprecation_level();
    // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:170-170
    static const ClassId& enum_entries();
    // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:172-172
    static const ClassId& atomic_boolean();
    // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:173-173
    static const ClassId& atomic_int();
    // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:174-174
    static const ClassId& atomic_long();
    // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:175-175
    static const ClassId& atomic_reference();
    // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:183-183
    static const ClassId& atomic_array();
    // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:184-184
    static const ClassId& atomic_int_array();
    // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:185-185
    static const ClassId& atomic_long_array();
    // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:192-192
    class Annotations final {
    public:
        // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:193-193
        static const ClassId& suppress();
        // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:194-194
        static const ClassId& published_api();
        // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:195-195
        static const ClassId& since_kotlin();
        // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:196-196
        static const ClassId& extension_function_type();
        // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:197-197
        static const ClassId& context_function_type_params();
        // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:198-198
        static const ClassId& deprecated();
        // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:199-199
        static const ClassId& deprecated_since_kotlin();
        // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:200-200
        static const ClassId& require_kotlin();
        // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:201-201
        static const ClassId& dsl_marker();
        // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:202-202
        static const ClassId& introduced_at();
        // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:204-204
        static const ClassId& numeric_class();
        // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:206-206
        static const ClassId& low_priority_in_overload_resolution();
        // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:208-208
        static const ClassId& consistent_copy_visibility();
        // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:209-209
        static const ClassId& exposed_copy_visibility();
        // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:211-211
        static const ClassId& hides_members();
        // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:212-212
        static const ClassId& dynamic_extension();
        // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:213-213
        static const ClassId& intrinsic_const_evaluation();
        // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:215-215
        static const ClassId& retention();
        // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:216-216
        static const ClassId& target();
        // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:217-217
        static const ClassId& repeatable();
        // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:218-218
        static const ClassId& must_be_documented();
        // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:219-219
        static const ClassId& expect_refinement();
        // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:221-221
        static const ClassId& volatile_name();
        // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:223-223
        static const ClassId& test();
        // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:225-225
        static const ClassId& raw_type_annotation();
        // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:226-226
        static const ClassId& flexible_nullability();
        // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:227-227
        static const ClassId& flexible_mutability();
        // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:228-228
        static const ClassId& flexible_array_element_variance();
        // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:229-229
        static const ClassId& enhanced_nullability();
        // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:230-230
        static const ClassId& no_infer();
        // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:232-232
        static const ClassId& function_n();
        // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:234-234
        static const ClassId& inline_only();
        // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:236-236
        static const ClassId& only_input_types();
        // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:238-238
        static const ClassId& restricts_suspension();
        // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:240-240
        static const ClassId& was_experimental();
        // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:242-242
        static const ClassId& must_use_return_values();
        // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:243-243
        static const ClassId& ignorable_return_value();
        // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:245-245
        static const ClassId& equality_bound();
        // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:247-247
        static const ClassId& accessible_lateinit_property_literal();
        // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:249-249
        static const ClassId& optional_expectation();
        // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:250-250
        static const ClassId& implicitly_actualized_by_jvm_declaration();
        // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:251-251
        static const ClassId& kotlin_actual();
        // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:253-253
        static const ClassId& jvm_static();
        // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:254-254
        static const ClassId& jvm_name();
        // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:255-255
        static const ClassId& transient();
        // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:257-257
        static const ClassId& js_export();
        // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:258-258
        static const ClassId& js_implicit_export();
        // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:259-259
        static const ClassId& js_export_ignore();
        // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:260-260
        static const ClassId& js_export_default();
        // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:261-261
        static const ClassId& js_no_dispatch_receiver();
        // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:262-262
        static const ClassId& js_no_runtime();
        // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:264-264
        static const ClassId& associated_object_key();
        // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:265-265
        static const ClassId& experimental_associated_objects();
        // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:269-269
        static const ClassId& jvm_builtin();
        // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:270-270
        static const ClassId& suppress_bytecode_generation();
        // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:272-272
        static const ClassId& used_from_compiler_generated_code();
        // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:280-280
        /** File annotation selecting the package stored in reflective class information. */
        static const ClassId& reflection_package_name();
        // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:282-282
        class ParameterNames final {
        public:
            // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:283-283
            static const Name& value();
            // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:285-285
            static const Name& retention_value();
            // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:286-286
            static const Name& target_allowed_targets();
            // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:288-288
            static const Name& equality_bound();
            // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:290-290
            static const Name& since_kotlin_version();
            // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:292-292
            static const Name& actualizations();
            // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:294-294
            static const Name& deprecated_message();
            // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:295-295
            static const Name& deprecated_level();
            // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:297-297
            static const Name& deprecated_since_kotlin_warning_since();
            // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:298-298
            static const Name& deprecated_since_kotlin_error_since();
            // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:299-299
            static const Name& deprecated_since_kotlin_hidden_since();
            // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:301-301
            static const Name& suppress_names();
            // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:303-303
            static const Name& parameter_name_name();
        };
    };
    // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:307-307
    class Callables final {
    public:
        // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:308-308
        static const CallableId& suspend();
        // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:309-309
        static const CallableId& coroutine_context();
        // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:311-311
        static const CallableId& clone();
        // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:313-313
        static const CallableId& not_name();
        // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:315-315
        static const CallableId& contract();
        // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:317-317
        static const CallableId& atomic_reference_compare_and_set();
        // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:318-318
        static const CallableId& atomic_reference_compare_and_exchange();
        // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:319-319
        static const CallableId& atomic_array_compare_and_set_at();
        // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:320-320
        static const CallableId& atomic_array_compare_and_exchange_at();
        // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:322-322
        static const CallableId& throw_no_when_branch_matched_exception();
    };
    // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:100-100
    static ClassId by_name(const std::u16string& name);
    // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:101-101
    static ClassId reflect_by_name(const std::u16string& name);
    // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:120-122
    static ClassId function_n(std::int32_t arity);
    // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:125-127
    static ClassId suspend_function_n(std::int32_t arity);
    // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:130-132
    static ClassId k_function_n(std::int32_t arity);
    // Transliterated from: core/names/src/org/jetbrains/kotlin/name/StandardClassIds.kt:135-137
    static ClassId k_suspend_function_n(std::int32_t arity);
};
}
