/*
 * Copyright 2010-2024 JetBrains s.r.o. and Kotlin Programming Language contributors.
 * Use of this source code is governed by the Apache 2.0 license that can be found in the license/LICENSE.txt file.
 */
// port-lint: source compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt
// Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:1-590
#pragma once

#include "IrTransformer.hpp"
#include <cstddef>
#include <functional>
#include <type_traits>

namespace org::jetbrains::kotlin::ir::visitors {
/**
 * Auto-generated by [org.jetbrains.kotlin.ir.generator.print.TransformerVoidPrinter]
 */
// NOTE(port): Nothing? admits only null; std::nullptr_t preserves that context.
// Actual Kotlin 'as' checks use C++ checked reference casts in the bodies.
// Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:19-586
class IrElementTransformerVoid : public IrTransformer<std::nullptr_t> {
 protected:
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:21-25
  template <typename T>
  T& transform_postfix(T& element, const std::function<void(T&)>& body) {
    static_assert(std::is_base_of_v<IrElement, T>);
    transform_children_void(element);
    body(element);
    return element;
  }
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:27-29
  void transform_children_void(IrElement& element);
 public:
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:31-34
  virtual IrElement& visit_element(IrElement& element);
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:36-37
  IrElement& visit_element(IrElement& element, std::nullptr_t) final override;
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:39-42
  virtual IrStatement& visit_declaration(declarations::IrDeclarationBase& declaration);
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:44-45
  IrStatement& visit_declaration(declarations::IrDeclarationBase& declaration, std::nullptr_t) final override;
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:47-48
  virtual IrStatement& visit_value_parameter(declarations::IrValueParameter& declaration);
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:50-51
  IrStatement& visit_value_parameter(declarations::IrValueParameter& declaration, std::nullptr_t) final override;
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:53-54
  virtual IrStatement& visit_class(declarations::IrClass& declaration);
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:56-57
  IrStatement& visit_class(declarations::IrClass& declaration, std::nullptr_t) final override;
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:59-60
  virtual IrStatement& visit_anonymous_initializer(declarations::IrAnonymousInitializer& declaration);
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:62-63
  IrStatement& visit_anonymous_initializer(declarations::IrAnonymousInitializer& declaration, std::nullptr_t) final override;
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:65-66
  virtual IrStatement& visit_type_parameter(declarations::IrTypeParameter& declaration);
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:68-69
  IrStatement& visit_type_parameter(declarations::IrTypeParameter& declaration, std::nullptr_t) final override;
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:71-72
  virtual IrStatement& visit_function(declarations::IrFunction& declaration);
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:74-75
  IrStatement& visit_function(declarations::IrFunction& declaration, std::nullptr_t) final override;
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:77-78
  virtual IrStatement& visit_constructor(declarations::IrConstructor& declaration);
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:80-81
  IrStatement& visit_constructor(declarations::IrConstructor& declaration, std::nullptr_t) final override;
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:83-84
  virtual IrStatement& visit_enum_entry(declarations::IrEnumEntry& declaration);
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:86-87
  IrStatement& visit_enum_entry(declarations::IrEnumEntry& declaration, std::nullptr_t) final override;
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:89-90
  virtual IrStatement& visit_field(declarations::IrField& declaration);
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:92-93
  IrStatement& visit_field(declarations::IrField& declaration, std::nullptr_t) final override;
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:95-96
  virtual IrStatement& visit_local_delegated_property(declarations::IrLocalDelegatedProperty& declaration);
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:98-99
  IrStatement& visit_local_delegated_property(declarations::IrLocalDelegatedProperty& declaration, std::nullptr_t) final override;
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:101-104
  virtual declarations::IrModuleFragment& visit_module_fragment(declarations::IrModuleFragment& declaration);
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:106-107
  declarations::IrModuleFragment& visit_module_fragment(declarations::IrModuleFragment& declaration, std::nullptr_t) final override;
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:109-110
  virtual IrStatement& visit_property(declarations::IrProperty& declaration);
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:112-113
  IrStatement& visit_property(declarations::IrProperty& declaration, std::nullptr_t) final override;
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:115-116
  virtual IrStatement& visit_script(declarations::IrScript& declaration);
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:118-119
  IrStatement& visit_script(declarations::IrScript& declaration, std::nullptr_t) final override;
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:121-122
  virtual IrStatement& visit_repl_snippet(declarations::IrReplSnippet& declaration);
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:124-125
  IrStatement& visit_repl_snippet(declarations::IrReplSnippet& declaration, std::nullptr_t) final override;
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:127-128
  virtual IrStatement& visit_simple_function(declarations::IrSimpleFunction& declaration);
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:130-131
  IrStatement& visit_simple_function(declarations::IrSimpleFunction& declaration, std::nullptr_t) final override;
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:133-134
  virtual IrStatement& visit_type_alias(declarations::IrTypeAlias& declaration);
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:136-137
  IrStatement& visit_type_alias(declarations::IrTypeAlias& declaration, std::nullptr_t) final override;
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:139-140
  virtual IrStatement& visit_variable(declarations::IrVariable& declaration);
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:142-143
  IrStatement& visit_variable(declarations::IrVariable& declaration, std::nullptr_t) final override;
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:145-148
  virtual declarations::IrPackageFragment& visit_package_fragment(declarations::IrPackageFragment& declaration);
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:150-151
  IrElement& visit_package_fragment(declarations::IrPackageFragment& declaration, std::nullptr_t) final override;
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:153-154
  virtual declarations::IrExternalPackageFragment& visit_external_package_fragment(declarations::IrExternalPackageFragment& declaration);
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:156-157
  declarations::IrExternalPackageFragment& visit_external_package_fragment(declarations::IrExternalPackageFragment& declaration, std::nullptr_t) final override;
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:159-160
  virtual declarations::IrFile& visit_file(declarations::IrFile& declaration);
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:162-163
  declarations::IrFile& visit_file(declarations::IrFile& declaration, std::nullptr_t) final override;
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:165-168
  virtual expressions::IrExpression& visit_expression(expressions::IrExpression& expression);
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:170-171
  expressions::IrExpression& visit_expression(expressions::IrExpression& expression, std::nullptr_t) final override;
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:173-176
  virtual expressions::IrBody& visit_body(expressions::IrBody& body);
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:178-179
  expressions::IrBody& visit_body(expressions::IrBody& body, std::nullptr_t) final override;
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:181-182
  virtual expressions::IrBody& visit_expression_body(expressions::IrExpressionBody& body);
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:184-185
  expressions::IrBody& visit_expression_body(expressions::IrExpressionBody& body, std::nullptr_t) final override;
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:187-188
  virtual expressions::IrBody& visit_block_body(expressions::IrBlockBody& body);
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:190-191
  expressions::IrBody& visit_block_body(expressions::IrBlockBody& body, std::nullptr_t) final override;
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:193-194
  virtual expressions::IrExpression& visit_declaration_reference(expressions::IrDeclarationReference& expression);
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:196-197
  expressions::IrExpression& visit_declaration_reference(expressions::IrDeclarationReference& expression, std::nullptr_t) final override;
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:199-200
  virtual expressions::IrExpression& visit_member_access(expressions::IrMemberAccessExpression<symbols::IrSymbol>& expression);
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:202-203
  IrElement& visit_member_access(expressions::IrMemberAccessExpression<symbols::IrSymbol>& expression, std::nullptr_t) final override;
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:205-206
  virtual expressions::IrExpression& visit_function_access(expressions::IrFunctionAccessExpression& expression);
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:208-209
  IrElement& visit_function_access(expressions::IrFunctionAccessExpression& expression, std::nullptr_t) final override;
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:211-212
  virtual expressions::IrExpression& visit_constructor_call(expressions::IrConstructorCall& expression);
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:214-215
  IrElement& visit_constructor_call(expressions::IrConstructorCall& expression, std::nullptr_t) final override;
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:217-218
  virtual expressions::IrExpression& visit_annotation(expressions::IrAnnotation& expression);
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:220-221
  IrElement& visit_annotation(expressions::IrAnnotation& expression, std::nullptr_t) final override;
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:223-224
  virtual expressions::IrExpression& visit_singleton_reference(expressions::IrGetSingletonValue& expression);
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:226-227
  expressions::IrExpression& visit_singleton_reference(expressions::IrGetSingletonValue& expression, std::nullptr_t) final override;
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:229-230
  virtual expressions::IrExpression& visit_get_object_value(expressions::IrGetObjectValue& expression);
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:232-233
  expressions::IrExpression& visit_get_object_value(expressions::IrGetObjectValue& expression, std::nullptr_t) final override;
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:235-236
  virtual expressions::IrExpression& visit_get_enum_value(expressions::IrGetEnumValue& expression);
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:238-239
  expressions::IrExpression& visit_get_enum_value(expressions::IrGetEnumValue& expression, std::nullptr_t) final override;
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:241-242
  virtual expressions::IrExpression& visit_raw_function_reference(expressions::IrRawFunctionReference& expression);
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:244-245
  expressions::IrExpression& visit_raw_function_reference(expressions::IrRawFunctionReference& expression, std::nullptr_t) final override;
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:247-248
  virtual expressions::IrExpression& visit_container_expression(expressions::IrContainerExpression& expression);
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:250-251
  expressions::IrExpression& visit_container_expression(expressions::IrContainerExpression& expression, std::nullptr_t) final override;
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:253-254
  virtual expressions::IrExpression& visit_block(expressions::IrBlock& expression);
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:256-257
  expressions::IrExpression& visit_block(expressions::IrBlock& expression, std::nullptr_t) final override;
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:259-260
  virtual expressions::IrExpression& visit_composite(expressions::IrComposite& expression);
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:262-263
  expressions::IrExpression& visit_composite(expressions::IrComposite& expression, std::nullptr_t) final override;
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:265-266
  virtual expressions::IrExpression& visit_returnable_block(expressions::IrReturnableBlock& expression);
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:268-269
  expressions::IrExpression& visit_returnable_block(expressions::IrReturnableBlock& expression, std::nullptr_t) final override;
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:271-272
  virtual expressions::IrExpression& visit_inlined_function_block(expressions::IrInlinedFunctionBlock& inlined_block);
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:274-275
  expressions::IrExpression& visit_inlined_function_block(expressions::IrInlinedFunctionBlock& inlined_block, std::nullptr_t) final override;
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:277-278
  virtual expressions::IrBody& visit_synthetic_body(expressions::IrSyntheticBody& body);
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:280-281
  expressions::IrBody& visit_synthetic_body(expressions::IrSyntheticBody& body, std::nullptr_t) final override;
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:283-284
  virtual expressions::IrExpression& visit_break_continue(expressions::IrBreakContinue& jump);
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:286-287
  expressions::IrExpression& visit_break_continue(expressions::IrBreakContinue& jump, std::nullptr_t) final override;
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:289-290
  virtual expressions::IrExpression& visit_break(expressions::IrBreak& jump);
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:292-293
  expressions::IrExpression& visit_break(expressions::IrBreak& jump, std::nullptr_t) final override;
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:295-296
  virtual expressions::IrExpression& visit_continue(expressions::IrContinue& jump);
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:298-299
  expressions::IrExpression& visit_continue(expressions::IrContinue& jump, std::nullptr_t) final override;
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:301-302
  virtual expressions::IrExpression& visit_call(expressions::IrCall& expression);
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:304-305
  IrElement& visit_call(expressions::IrCall& expression, std::nullptr_t) final override;
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:307-308
  virtual expressions::IrExpression& visit_callable_reference(expressions::IrCallableReference<symbols::IrSymbol>& expression);
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:310-311
  IrElement& visit_callable_reference(expressions::IrCallableReference<symbols::IrSymbol>& expression, std::nullptr_t) final override;
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:313-314
  virtual expressions::IrExpression& visit_function_reference(expressions::IrFunctionReference& expression);
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:316-317
  IrElement& visit_function_reference(expressions::IrFunctionReference& expression, std::nullptr_t) final override;
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:319-320
  virtual expressions::IrExpression& visit_property_reference(expressions::IrPropertyReference& expression);
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:322-323
  IrElement& visit_property_reference(expressions::IrPropertyReference& expression, std::nullptr_t) final override;
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:325-326
  virtual expressions::IrExpression& visit_local_delegated_property_reference(expressions::IrLocalDelegatedPropertyReference& expression);
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:328-329
  IrElement& visit_local_delegated_property_reference(expressions::IrLocalDelegatedPropertyReference& expression, std::nullptr_t) final override;
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:331-332
  virtual expressions::IrExpression& visit_rich_callable_reference(expressions::IrRichCallableReference<symbols::IrSymbol>& expression);
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:334-335
  expressions::IrExpression& visit_rich_callable_reference(expressions::IrRichCallableReference<symbols::IrSymbol>& expression, std::nullptr_t) final override;
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:337-338
  virtual expressions::IrExpression& visit_rich_function_reference(expressions::IrRichFunctionReference& expression);
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:340-341
  expressions::IrExpression& visit_rich_function_reference(expressions::IrRichFunctionReference& expression, std::nullptr_t) final override;
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:343-344
  virtual expressions::IrExpression& visit_rich_property_reference(expressions::IrRichPropertyReference& expression);
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:346-347
  expressions::IrExpression& visit_rich_property_reference(expressions::IrRichPropertyReference& expression, std::nullptr_t) final override;
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:349-350
  virtual expressions::IrExpression& visit_class_reference(expressions::IrClassReference& expression);
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:352-353
  expressions::IrExpression& visit_class_reference(expressions::IrClassReference& expression, std::nullptr_t) final override;
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:355-356
  virtual expressions::IrExpression& visit_const(expressions::IrConst& expression);
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:358-359
  expressions::IrExpression& visit_const(expressions::IrConst& expression, std::nullptr_t) final override;
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:361-364
  virtual expressions::IrConstantValue& visit_constant_value(expressions::IrConstantValue& expression);
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:366-367
  expressions::IrConstantValue& visit_constant_value(expressions::IrConstantValue& expression, std::nullptr_t) final override;
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:369-370
  virtual expressions::IrConstantValue& visit_constant_primitive(expressions::IrConstantPrimitive& expression);
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:372-373
  expressions::IrConstantValue& visit_constant_primitive(expressions::IrConstantPrimitive& expression, std::nullptr_t) final override;
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:375-376
  virtual expressions::IrConstantValue& visit_constant_object(expressions::IrConstantObject& expression);
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:378-379
  expressions::IrConstantValue& visit_constant_object(expressions::IrConstantObject& expression, std::nullptr_t) final override;
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:381-382
  virtual expressions::IrConstantValue& visit_constant_array(expressions::IrConstantArray& expression);
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:384-385
  expressions::IrConstantValue& visit_constant_array(expressions::IrConstantArray& expression, std::nullptr_t) final override;
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:387-388
  virtual expressions::IrExpression& visit_delegating_constructor_call(expressions::IrDelegatingConstructorCall& expression);
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:390-391
  IrElement& visit_delegating_constructor_call(expressions::IrDelegatingConstructorCall& expression, std::nullptr_t) final override;
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:393-394
  virtual expressions::IrExpression& visit_dynamic_expression(expressions::IrDynamicExpression& expression);
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:396-397
  expressions::IrExpression& visit_dynamic_expression(expressions::IrDynamicExpression& expression, std::nullptr_t) final override;
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:399-400
  virtual expressions::IrExpression& visit_dynamic_operator_expression(expressions::IrDynamicOperatorExpression& expression);
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:402-403
  expressions::IrExpression& visit_dynamic_operator_expression(expressions::IrDynamicOperatorExpression& expression, std::nullptr_t) final override;
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:405-406
  virtual expressions::IrExpression& visit_dynamic_member_expression(expressions::IrDynamicMemberExpression& expression);
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:408-409
  expressions::IrExpression& visit_dynamic_member_expression(expressions::IrDynamicMemberExpression& expression, std::nullptr_t) final override;
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:411-412
  virtual expressions::IrExpression& visit_enum_constructor_call(expressions::IrEnumConstructorCall& expression);
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:414-415
  IrElement& visit_enum_constructor_call(expressions::IrEnumConstructorCall& expression, std::nullptr_t) final override;
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:417-418
  virtual expressions::IrExpression& visit_error_expression(expressions::IrErrorExpression& expression);
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:420-421
  expressions::IrExpression& visit_error_expression(expressions::IrErrorExpression& expression, std::nullptr_t) final override;
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:423-424
  virtual expressions::IrExpression& visit_error_call_expression(expressions::IrErrorCallExpression& expression);
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:426-427
  expressions::IrExpression& visit_error_call_expression(expressions::IrErrorCallExpression& expression, std::nullptr_t) final override;
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:429-430
  virtual expressions::IrExpression& visit_field_access(expressions::IrFieldAccessExpression& expression);
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:432-433
  expressions::IrExpression& visit_field_access(expressions::IrFieldAccessExpression& expression, std::nullptr_t) final override;
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:435-436
  virtual expressions::IrExpression& visit_get_field(expressions::IrGetField& expression);
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:438-439
  expressions::IrExpression& visit_get_field(expressions::IrGetField& expression, std::nullptr_t) final override;
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:441-442
  virtual expressions::IrExpression& visit_set_field(expressions::IrSetField& expression);
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:444-445
  expressions::IrExpression& visit_set_field(expressions::IrSetField& expression, std::nullptr_t) final override;
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:447-448
  virtual expressions::IrExpression& visit_function_expression(expressions::IrFunctionExpression& expression);
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:450-451
  IrElement& visit_function_expression(expressions::IrFunctionExpression& expression, std::nullptr_t) final override;
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:453-454
  virtual expressions::IrExpression& visit_get_class(expressions::IrGetClass& expression);
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:456-457
  expressions::IrExpression& visit_get_class(expressions::IrGetClass& expression, std::nullptr_t) final override;
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:459-460
  virtual expressions::IrExpression& visit_instance_initializer_call(expressions::IrInstanceInitializerCall& expression);
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:462-463
  expressions::IrExpression& visit_instance_initializer_call(expressions::IrInstanceInitializerCall& expression, std::nullptr_t) final override;
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:465-466
  virtual expressions::IrExpression& visit_loop(expressions::IrLoop& loop);
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:468-469
  expressions::IrExpression& visit_loop(expressions::IrLoop& loop, std::nullptr_t) final override;
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:471-472
  virtual expressions::IrExpression& visit_while_loop(expressions::IrWhileLoop& loop);
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:474-475
  expressions::IrExpression& visit_while_loop(expressions::IrWhileLoop& loop, std::nullptr_t) final override;
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:477-478
  virtual expressions::IrExpression& visit_do_while_loop(expressions::IrDoWhileLoop& loop);
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:480-481
  expressions::IrExpression& visit_do_while_loop(expressions::IrDoWhileLoop& loop, std::nullptr_t) final override;
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:483-484
  virtual expressions::IrExpression& visit_return(expressions::IrReturn& expression);
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:486-487
  expressions::IrExpression& visit_return(expressions::IrReturn& expression, std::nullptr_t) final override;
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:489-490
  virtual expressions::IrExpression& visit_string_concatenation(expressions::IrStringConcatenation& expression);
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:492-493
  expressions::IrExpression& visit_string_concatenation(expressions::IrStringConcatenation& expression, std::nullptr_t) final override;
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:495-496
  virtual expressions::IrExpression& visit_suspension_point(expressions::IrSuspensionPoint& expression);
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:498-499
  expressions::IrExpression& visit_suspension_point(expressions::IrSuspensionPoint& expression, std::nullptr_t) final override;
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:501-502
  virtual expressions::IrExpression& visit_suspendable_expression(expressions::IrSuspendableExpression& expression);
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:504-505
  expressions::IrExpression& visit_suspendable_expression(expressions::IrSuspendableExpression& expression, std::nullptr_t) final override;
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:507-508
  virtual expressions::IrExpression& visit_throw(expressions::IrThrow& expression);
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:510-511
  expressions::IrExpression& visit_throw(expressions::IrThrow& expression, std::nullptr_t) final override;
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:513-514
  virtual expressions::IrExpression& visit_try(expressions::IrTry& a_try);
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:516-517
  expressions::IrExpression& visit_try(expressions::IrTry& a_try, std::nullptr_t) final override;
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:519-522
  virtual expressions::IrCatch& visit_catch(expressions::IrCatch& a_catch);
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:524-525
  expressions::IrCatch& visit_catch(expressions::IrCatch& a_catch, std::nullptr_t) final override;
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:527-528
  virtual expressions::IrExpression& visit_type_operator(expressions::IrTypeOperatorCall& expression);
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:530-531
  expressions::IrExpression& visit_type_operator(expressions::IrTypeOperatorCall& expression, std::nullptr_t) final override;
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:533-534
  virtual expressions::IrExpression& visit_value_access(expressions::IrValueAccessExpression& expression);
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:536-537
  expressions::IrExpression& visit_value_access(expressions::IrValueAccessExpression& expression, std::nullptr_t) final override;
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:539-540
  virtual expressions::IrExpression& visit_get_value(expressions::IrGetValue& expression);
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:542-543
  expressions::IrExpression& visit_get_value(expressions::IrGetValue& expression, std::nullptr_t) final override;
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:545-546
  virtual expressions::IrExpression& visit_set_value(expressions::IrSetValue& expression);
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:548-549
  expressions::IrExpression& visit_set_value(expressions::IrSetValue& expression, std::nullptr_t) final override;
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:551-552
  virtual expressions::IrExpression& visit_vararg(expressions::IrVararg& expression);
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:554-555
  expressions::IrExpression& visit_vararg(expressions::IrVararg& expression, std::nullptr_t) final override;
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:557-560
  virtual expressions::IrSpreadElement& visit_spread_element(expressions::IrSpreadElement& spread);
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:562-563
  expressions::IrSpreadElement& visit_spread_element(expressions::IrSpreadElement& spread, std::nullptr_t) final override;
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:565-566
  virtual expressions::IrExpression& visit_when(expressions::IrWhen& expression);
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:568-569
  expressions::IrExpression& visit_when(expressions::IrWhen& expression, std::nullptr_t) final override;
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:571-574
  virtual expressions::IrBranch& visit_branch(expressions::IrBranch& branch);
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:576-577
  expressions::IrBranch& visit_branch(expressions::IrBranch& branch, std::nullptr_t) final override;
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:579-582
  virtual expressions::IrElseBranch& visit_else_branch(expressions::IrElseBranch& branch);
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:584-585
  expressions::IrElseBranch& visit_else_branch(expressions::IrElseBranch& branch, std::nullptr_t) final override;
};

// Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrElementTransformerVoid.kt:588-590
void transform_children_void(IrElement& element,
                             IrElementTransformerVoid& transformer);
}  // namespace org::jetbrains::kotlin::ir::visitors
