/*
 * Copyright 2010-2024 JetBrains s.r.o. and Kotlin Programming Language contributors.
 * Use of this source code is governed by the Apache 2.0 license that can be found in the license/LICENSE.txt file.
 */
// port-lint: source compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrTransformer.kt
// Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrTransformer.kt:1-311
#pragma once

#include "Deprecated.hpp"
#include "IrVisitor.hpp"
#include "../expressions/IrAnnotation.hpp"
#include "../declarations/IrAnonymousInitializer.hpp"
#include "../expressions/IrBlock.hpp"
#include "../expressions/IrBlockBody.hpp"
#include "../expressions/IrBody.hpp"
#include "../expressions/IrBranch.hpp"
#include "../expressions/IrBreak.hpp"
#include "../expressions/IrBreakContinue.hpp"
#include "../expressions/IrCall.hpp"
#include "../expressions/IrCallableReference.hpp"
#include "../expressions/IrCatch.hpp"
#include "../declarations/IrClass.hpp"
#include "../expressions/IrClassReference.hpp"
#include "../expressions/IrComposite.hpp"
#include "../expressions/IrConst.hpp"
#include "../expressions/IrConstantArray.hpp"
#include "../expressions/IrConstantObject.hpp"
#include "../expressions/IrConstantPrimitive.hpp"
#include "../expressions/IrConstantValue.hpp"
#include "../declarations/IrConstructor.hpp"
#include "../expressions/IrConstructorCall.hpp"
#include "../expressions/IrContainerExpression.hpp"
#include "../expressions/IrContinue.hpp"
#include "../declarations/IrDeclarationBase.hpp"
#include "../expressions/IrDeclarationReference.hpp"
#include "../expressions/IrDelegatingConstructorCall.hpp"
#include "../expressions/IrDoWhileLoop.hpp"
#include "../expressions/IrDynamicExpression.hpp"
#include "../expressions/IrDynamicMemberExpression.hpp"
#include "../expressions/IrDynamicOperatorExpression.hpp"
#include "../IrElement.hpp"
#include "../expressions/IrElseBranch.hpp"
#include "../expressions/IrEnumConstructorCall.hpp"
#include "../declarations/IrEnumEntry.hpp"
#include "../expressions/IrErrorCallExpression.hpp"
#include "../expressions/IrErrorExpression.hpp"
#include "../expressions/IrExpression.hpp"
#include "../expressions/IrExpressionBody.hpp"
#include "../declarations/IrExternalPackageFragment.hpp"
#include "../declarations/IrField.hpp"
#include "../expressions/IrFieldAccessExpression.hpp"
#include "../declarations/IrFile.hpp"
#include "../declarations/IrFunction.hpp"
#include "../expressions/IrFunctionAccessExpression.hpp"
#include "../expressions/IrFunctionExpression.hpp"
#include "../expressions/IrFunctionReference.hpp"
#include "../expressions/IrGetClass.hpp"
#include "../expressions/IrGetEnumValue.hpp"
#include "../expressions/IrGetField.hpp"
#include "../expressions/IrGetObjectValue.hpp"
#include "../expressions/IrGetSingletonValue.hpp"
#include "../expressions/IrGetValue.hpp"
#include "../expressions/IrInlinedFunctionBlock.hpp"
#include "../expressions/IrInstanceInitializerCall.hpp"
#include "../declarations/IrLocalDelegatedProperty.hpp"
#include "../expressions/IrLocalDelegatedPropertyReference.hpp"
#include "../expressions/IrLoop.hpp"
#include "../expressions/IrMemberAccessExpression.hpp"
#include "../declarations/IrModuleFragment.hpp"
#include "../declarations/IrPackageFragment.hpp"
#include "../declarations/IrProperty.hpp"
#include "../expressions/IrPropertyReference.hpp"
#include "../expressions/IrRawFunctionReference.hpp"
#include "../declarations/IrReplSnippet.hpp"
#include "../expressions/IrReturn.hpp"
#include "../expressions/IrReturnableBlock.hpp"
#include "../expressions/IrRichCallableReference.hpp"
#include "../expressions/IrRichFunctionReference.hpp"
#include "../expressions/IrRichPropertyReference.hpp"
#include "../declarations/IrScript.hpp"
#include "../expressions/IrSetField.hpp"
#include "../expressions/IrSetValue.hpp"
#include "../declarations/IrSimpleFunction.hpp"
#include "../expressions/IrSpreadElement.hpp"
#include "../IrStatement.hpp"
#include "../expressions/IrStringConcatenation.hpp"
#include "../expressions/IrSuspendableExpression.hpp"
#include "../expressions/IrSuspensionPoint.hpp"
#include "../expressions/IrSyntheticBody.hpp"
#include "../expressions/IrThrow.hpp"
#include "../expressions/IrTry.hpp"
#include "../declarations/IrTypeAlias.hpp"
#include "../expressions/IrTypeOperatorCall.hpp"
#include "../declarations/IrTypeParameter.hpp"
#include "../expressions/IrValueAccessExpression.hpp"
#include "../declarations/IrValueParameter.hpp"
#include "../expressions/IrVararg.hpp"
#include "../declarations/IrVariable.hpp"
#include "../expressions/IrWhen.hpp"
#include "../expressions/IrWhileLoop.hpp"

namespace org::jetbrains::kotlin::ir::visitors {
/**
 * Auto-generated by [org.jetbrains.kotlin.ir.generator.print.TransformerPrinter]
 */
// NOTE(port): Reference results preserve source node identity and covariant
// return types. The actual node definitions and star-projection views are
// required before this generic transformer can be instantiated.
// Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrTransformer.kt:19-311
template <typename D>
class IrTransformer : public IrVisitor<IrElement&, D>,
                      public IrElementTransformer<D> {
 public:
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrTransformer.kt:21-24
  IrElement& visit_element(IrElement& element, D data) override {
    element.transform_children(*this, data);
    return element;
  }
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrTransformer.kt:26-29
  IrStatement& visit_declaration(declarations::IrDeclarationBase& declaration, D data) override {
    declaration.transform_children(*this, data);
    return declaration;
  }
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrTransformer.kt:31-32
  IrStatement& visit_value_parameter(declarations::IrValueParameter& declaration, D data) override {
    return visit_declaration(declaration, data);
  }
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrTransformer.kt:34-35
  IrStatement& visit_class(declarations::IrClass& declaration, D data) override {
    return visit_declaration(declaration, data);
  }
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrTransformer.kt:37-38
  IrStatement& visit_anonymous_initializer(declarations::IrAnonymousInitializer& declaration, D data) override {
    return visit_declaration(declaration, data);
  }
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrTransformer.kt:40-41
  IrStatement& visit_type_parameter(declarations::IrTypeParameter& declaration, D data) override {
    return visit_declaration(declaration, data);
  }
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrTransformer.kt:43-44
  IrStatement& visit_function(declarations::IrFunction& declaration, D data) override {
    return visit_declaration(declaration, data);
  }
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrTransformer.kt:46-47
  IrStatement& visit_constructor(declarations::IrConstructor& declaration, D data) override {
    return visit_function(declaration, data);
  }
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrTransformer.kt:49-50
  IrStatement& visit_enum_entry(declarations::IrEnumEntry& declaration, D data) override {
    return visit_declaration(declaration, data);
  }
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrTransformer.kt:52-53
  IrStatement& visit_field(declarations::IrField& declaration, D data) override {
    return visit_declaration(declaration, data);
  }
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrTransformer.kt:55-56
  IrStatement& visit_local_delegated_property(declarations::IrLocalDelegatedProperty& declaration, D data) override {
    return visit_declaration(declaration, data);
  }
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrTransformer.kt:58-61
  declarations::IrModuleFragment& visit_module_fragment(declarations::IrModuleFragment& declaration, D data) override {
    declaration.transform_children(*this, data);
    return declaration;
  }
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrTransformer.kt:63-64
  IrStatement& visit_property(declarations::IrProperty& declaration, D data) override {
    return visit_declaration(declaration, data);
  }
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrTransformer.kt:66-67
  IrStatement& visit_script(declarations::IrScript& declaration, D data) override {
    return visit_declaration(declaration, data);
  }
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrTransformer.kt:69-70
  IrStatement& visit_repl_snippet(declarations::IrReplSnippet& declaration, D data) override {
    return visit_declaration(declaration, data);
  }
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrTransformer.kt:72-73
  IrStatement& visit_simple_function(declarations::IrSimpleFunction& declaration, D data) override {
    return visit_function(declaration, data);
  }
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrTransformer.kt:75-76
  IrStatement& visit_type_alias(declarations::IrTypeAlias& declaration, D data) override {
    return visit_declaration(declaration, data);
  }
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrTransformer.kt:78-79
  IrStatement& visit_variable(declarations::IrVariable& declaration, D data) override {
    return visit_declaration(declaration, data);
  }
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrTransformer.kt:81-82
  IrElement& visit_package_fragment(declarations::IrPackageFragment& declaration, D data) override {
    return visit_element(declaration, data);
  }
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrTransformer.kt:84-87
  declarations::IrExternalPackageFragment& visit_external_package_fragment(declarations::IrExternalPackageFragment& declaration, D data) override {
    declaration.transform_children(*this, data);
    return declaration;
  }
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrTransformer.kt:89-92
  declarations::IrFile& visit_file(declarations::IrFile& declaration, D data) override {
    declaration.transform_children(*this, data);
    return declaration;
  }
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrTransformer.kt:94-97
  expressions::IrExpression& visit_expression(expressions::IrExpression& expression, D data) override {
    expression.transform_children(*this, data);
    return expression;
  }
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrTransformer.kt:99-102
  expressions::IrBody& visit_body(expressions::IrBody& body, D data) override {
    body.transform_children(*this, data);
    return body;
  }
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrTransformer.kt:104-105
  expressions::IrBody& visit_expression_body(expressions::IrExpressionBody& body, D data) override {
    return visit_body(body, data);
  }
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrTransformer.kt:107-108
  expressions::IrBody& visit_block_body(expressions::IrBlockBody& body, D data) override {
    return visit_body(body, data);
  }
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrTransformer.kt:110-111
  expressions::IrExpression& visit_declaration_reference(expressions::IrDeclarationReference& expression, D data) override {
    return visit_expression(expression, data);
  }
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrTransformer.kt:113-114
  IrElement& visit_member_access(expressions::IrMemberAccessExpression<symbols::IrSymbol>& expression, D data) override {
    return visit_declaration_reference(expression, data);
  }
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrTransformer.kt:116-117
  IrElement& visit_function_access(expressions::IrFunctionAccessExpression& expression, D data) override {
    return visit_member_access(expression, data);
  }
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrTransformer.kt:119-120
  IrElement& visit_constructor_call(expressions::IrConstructorCall& expression, D data) override {
    return visit_function_access(expression, data);
  }
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrTransformer.kt:122-123
  IrElement& visit_annotation(expressions::IrAnnotation& expression, D data) override {
    return visit_constructor_call(expression, data);
  }
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrTransformer.kt:125-126
  expressions::IrExpression& visit_singleton_reference(expressions::IrGetSingletonValue& expression, D data) override {
    return visit_declaration_reference(expression, data);
  }
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrTransformer.kt:128-129
  expressions::IrExpression& visit_get_object_value(expressions::IrGetObjectValue& expression, D data) override {
    return visit_singleton_reference(expression, data);
  }
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrTransformer.kt:131-132
  expressions::IrExpression& visit_get_enum_value(expressions::IrGetEnumValue& expression, D data) override {
    return visit_singleton_reference(expression, data);
  }
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrTransformer.kt:134-135
  expressions::IrExpression& visit_raw_function_reference(expressions::IrRawFunctionReference& expression, D data) override {
    return visit_declaration_reference(expression, data);
  }
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrTransformer.kt:137-138
  expressions::IrExpression& visit_container_expression(expressions::IrContainerExpression& expression, D data) override {
    return visit_expression(expression, data);
  }
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrTransformer.kt:140-141
  expressions::IrExpression& visit_block(expressions::IrBlock& expression, D data) override {
    return visit_container_expression(expression, data);
  }
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrTransformer.kt:143-144
  expressions::IrExpression& visit_composite(expressions::IrComposite& expression, D data) override {
    return visit_container_expression(expression, data);
  }
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrTransformer.kt:146-147
  expressions::IrExpression& visit_returnable_block(expressions::IrReturnableBlock& expression, D data) override {
    return visit_block(expression, data);
  }
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrTransformer.kt:149-150
  expressions::IrExpression& visit_inlined_function_block(expressions::IrInlinedFunctionBlock& inlined_block, D data) override {
    return visit_block(inlined_block, data);
  }
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrTransformer.kt:152-153
  expressions::IrBody& visit_synthetic_body(expressions::IrSyntheticBody& body, D data) override {
    return visit_body(body, data);
  }
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrTransformer.kt:155-156
  expressions::IrExpression& visit_break_continue(expressions::IrBreakContinue& jump, D data) override {
    return visit_expression(jump, data);
  }
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrTransformer.kt:158-159
  expressions::IrExpression& visit_break(expressions::IrBreak& jump, D data) override {
    return visit_break_continue(jump, data);
  }
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrTransformer.kt:161-162
  expressions::IrExpression& visit_continue(expressions::IrContinue& jump, D data) override {
    return visit_break_continue(jump, data);
  }
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrTransformer.kt:164-165
  IrElement& visit_call(expressions::IrCall& expression, D data) override {
    return visit_function_access(expression, data);
  }
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrTransformer.kt:167-168
  IrElement& visit_callable_reference(expressions::IrCallableReference<symbols::IrSymbol>& expression, D data) override {
    return visit_member_access(expression, data);
  }
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrTransformer.kt:170-171
  IrElement& visit_function_reference(expressions::IrFunctionReference& expression, D data) override {
    return visit_callable_reference(expression, data);
  }
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrTransformer.kt:173-174
  IrElement& visit_property_reference(expressions::IrPropertyReference& expression, D data) override {
    return visit_callable_reference(expression, data);
  }
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrTransformer.kt:176-177
  IrElement& visit_local_delegated_property_reference(expressions::IrLocalDelegatedPropertyReference& expression, D data) override {
    return visit_callable_reference(expression, data);
  }
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrTransformer.kt:179-180
  expressions::IrExpression& visit_rich_callable_reference(expressions::IrRichCallableReference<symbols::IrSymbol>& expression, D data) override {
    return visit_expression(expression, data);
  }
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrTransformer.kt:182-183
  expressions::IrExpression& visit_rich_function_reference(expressions::IrRichFunctionReference& expression, D data) override {
    return visit_rich_callable_reference(expression, data);
  }
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrTransformer.kt:185-186
  expressions::IrExpression& visit_rich_property_reference(expressions::IrRichPropertyReference& expression, D data) override {
    return visit_rich_callable_reference(expression, data);
  }
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrTransformer.kt:188-189
  expressions::IrExpression& visit_class_reference(expressions::IrClassReference& expression, D data) override {
    return visit_declaration_reference(expression, data);
  }
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrTransformer.kt:191-192
  expressions::IrExpression& visit_const(expressions::IrConst& expression, D data) override {
    return visit_expression(expression, data);
  }
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrTransformer.kt:194-197
  expressions::IrConstantValue& visit_constant_value(expressions::IrConstantValue& expression, D data) override {
    expression.transform_children(*this, data);
    return expression;
  }
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrTransformer.kt:199-200
  expressions::IrConstantValue& visit_constant_primitive(expressions::IrConstantPrimitive& expression, D data) override {
    return visit_constant_value(expression, data);
  }
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrTransformer.kt:202-203
  expressions::IrConstantValue& visit_constant_object(expressions::IrConstantObject& expression, D data) override {
    return visit_constant_value(expression, data);
  }
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrTransformer.kt:205-206
  expressions::IrConstantValue& visit_constant_array(expressions::IrConstantArray& expression, D data) override {
    return visit_constant_value(expression, data);
  }
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrTransformer.kt:208-209
  IrElement& visit_delegating_constructor_call(expressions::IrDelegatingConstructorCall& expression, D data) override {
    return visit_function_access(expression, data);
  }
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrTransformer.kt:211-212
  expressions::IrExpression& visit_dynamic_expression(expressions::IrDynamicExpression& expression, D data) override {
    return visit_expression(expression, data);
  }
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrTransformer.kt:214-215
  expressions::IrExpression& visit_dynamic_operator_expression(expressions::IrDynamicOperatorExpression& expression, D data) override {
    return visit_dynamic_expression(expression, data);
  }
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrTransformer.kt:217-218
  expressions::IrExpression& visit_dynamic_member_expression(expressions::IrDynamicMemberExpression& expression, D data) override {
    return visit_dynamic_expression(expression, data);
  }
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrTransformer.kt:220-221
  IrElement& visit_enum_constructor_call(expressions::IrEnumConstructorCall& expression, D data) override {
    return visit_function_access(expression, data);
  }
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrTransformer.kt:223-224
  expressions::IrExpression& visit_error_expression(expressions::IrErrorExpression& expression, D data) override {
    return visit_expression(expression, data);
  }
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrTransformer.kt:226-227
  expressions::IrExpression& visit_error_call_expression(expressions::IrErrorCallExpression& expression, D data) override {
    return visit_error_expression(expression, data);
  }
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrTransformer.kt:229-230
  expressions::IrExpression& visit_field_access(expressions::IrFieldAccessExpression& expression, D data) override {
    return visit_declaration_reference(expression, data);
  }
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrTransformer.kt:232-233
  expressions::IrExpression& visit_get_field(expressions::IrGetField& expression, D data) override {
    return visit_field_access(expression, data);
  }
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrTransformer.kt:235-236
  expressions::IrExpression& visit_set_field(expressions::IrSetField& expression, D data) override {
    return visit_field_access(expression, data);
  }
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrTransformer.kt:238-239
  IrElement& visit_function_expression(expressions::IrFunctionExpression& expression, D data) override {
    return visit_expression(expression, data);
  }
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrTransformer.kt:241-242
  expressions::IrExpression& visit_get_class(expressions::IrGetClass& expression, D data) override {
    return visit_expression(expression, data);
  }
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrTransformer.kt:244-245
  expressions::IrExpression& visit_instance_initializer_call(expressions::IrInstanceInitializerCall& expression, D data) override {
    return visit_expression(expression, data);
  }
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrTransformer.kt:247-248
  expressions::IrExpression& visit_loop(expressions::IrLoop& loop, D data) override {
    return visit_expression(loop, data);
  }
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrTransformer.kt:250-251
  expressions::IrExpression& visit_while_loop(expressions::IrWhileLoop& loop, D data) override {
    return visit_loop(loop, data);
  }
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrTransformer.kt:253-254
  expressions::IrExpression& visit_do_while_loop(expressions::IrDoWhileLoop& loop, D data) override {
    return visit_loop(loop, data);
  }
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrTransformer.kt:256-257
  expressions::IrExpression& visit_return(expressions::IrReturn& expression, D data) override {
    return visit_expression(expression, data);
  }
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrTransformer.kt:259-260
  expressions::IrExpression& visit_string_concatenation(expressions::IrStringConcatenation& expression, D data) override {
    return visit_expression(expression, data);
  }
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrTransformer.kt:262-263
  expressions::IrExpression& visit_suspension_point(expressions::IrSuspensionPoint& expression, D data) override {
    return visit_expression(expression, data);
  }
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrTransformer.kt:265-266
  expressions::IrExpression& visit_suspendable_expression(expressions::IrSuspendableExpression& expression, D data) override {
    return visit_expression(expression, data);
  }
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrTransformer.kt:268-269
  expressions::IrExpression& visit_throw(expressions::IrThrow& expression, D data) override {
    return visit_expression(expression, data);
  }
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrTransformer.kt:271-272
  expressions::IrExpression& visit_try(expressions::IrTry& a_try, D data) override {
    return visit_expression(a_try, data);
  }
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrTransformer.kt:274-277
  expressions::IrCatch& visit_catch(expressions::IrCatch& a_catch, D data) override {
    a_catch.transform_children(*this, data);
    return a_catch;
  }
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrTransformer.kt:279-280
  expressions::IrExpression& visit_type_operator(expressions::IrTypeOperatorCall& expression, D data) override {
    return visit_expression(expression, data);
  }
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrTransformer.kt:282-283
  expressions::IrExpression& visit_value_access(expressions::IrValueAccessExpression& expression, D data) override {
    return visit_declaration_reference(expression, data);
  }
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrTransformer.kt:285-286
  expressions::IrExpression& visit_get_value(expressions::IrGetValue& expression, D data) override {
    return visit_value_access(expression, data);
  }
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrTransformer.kt:288-289
  expressions::IrExpression& visit_set_value(expressions::IrSetValue& expression, D data) override {
    return visit_value_access(expression, data);
  }
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrTransformer.kt:291-292
  expressions::IrExpression& visit_vararg(expressions::IrVararg& expression, D data) override {
    return visit_expression(expression, data);
  }
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrTransformer.kt:294-297
  expressions::IrSpreadElement& visit_spread_element(expressions::IrSpreadElement& spread, D data) override {
    spread.transform_children(*this, data);
    return spread;
  }
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrTransformer.kt:299-300
  expressions::IrExpression& visit_when(expressions::IrWhen& expression, D data) override {
    return visit_expression(expression, data);
  }
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrTransformer.kt:302-305
  expressions::IrBranch& visit_branch(expressions::IrBranch& branch, D data) override {
    branch.transform_children(*this, data);
    return branch;
  }
  // Transliterated from: compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/visitors/IrTransformer.kt:307-310
  expressions::IrElseBranch& visit_else_branch(expressions::IrElseBranch& branch, D data) override {
    branch.transform_children(*this, data);
    return branch;
  }
};
}  // namespace org::jetbrains::kotlin::ir::visitors
