#pragma once
#include "kotlinx/coroutines/flow/Flow.hpp"
#include "kotlinx/coroutines/flow/operators/Combine.hpp"

namespace kotlinx {
namespace coroutines {
namespace flow {

/**
 * Zips values from the current flow with [other] flow using provided [transform].
 */
template <typename T1, typename T2, typename R>
Flow<R>* zip(Flow<T1>* flow, Flow<T2>* other, std::function<R(T1, T2)> transform) {
    return internal::zip_impl(flow, other, transform);
}

/**
 * Returns a Flow whose values are generated with [transform] function by combining
 * the most recently emitted values by each flow.
 */
template <typename T1, typename T2, typename R>
Flow<R>* combine(Flow<T1>* flow, Flow<T2>* other, std::function<R(T1, T2)> transform) {
    return kotlinx::coroutines::flow::combine(flow, other, transform);
}

/**
 * Returns a Flow whose values are generated by [transform] function that process
 * the most recently emitted values by each flow.
 */
template <typename T1, typename T2, typename R>
Flow<R>* combineTransform(Flow<T1>* flow, Flow<T2>* other, std::function<void(FlowCollector<R>*, T1, T2)> transform) {
    // TODO: Implement combineTransform (requires custom flow or flatMap)
    return nullptr;
}

/**
 * Returns a [Flow] whose values are generated with [transform] function by combining
 * the most recently emitted values by each flow.
 */
template <typename T1, typename T2, typename T3, typename R>
Flow<R>* combine(Flow<T1>* f1, Flow<T2>* f2, Flow<T3>* f3, std::function<R(T1, T2, T3)> transform) {
    // TODO: Implement 3-way combine (requires internal::combine_impl support for N-arity)
    return nullptr; // Placeholder for systematic porting
}

/**
 * Returns a [Flow] whose values are generated with [transform] function by combining
 * the most recently emitted values by each flow.
 */
template <typename T1, typename T2, typename T3, typename T4, typename R>
Flow<R>* combine(Flow<T1>* f1, Flow<T2>* f2, Flow<T3>* f3, Flow<T4>* f4, std::function<R(T1, T2, T3, T4)> transform) {
    // TODO: Implement 4-way combine
    return nullptr;
}

/**
 * Returns a [Flow] whose values are generated with [transform] function by combining
 * the most recently emitted values by each flow.
 */
template <typename T, typename R>
Flow<R>* combine(std::vector<Flow<T>*> flows, std::function<R(std::vector<T>)> transform) {
    // TODO: Implement vector-based combine (combineInternal)
    return nullptr;
}


} // namespace flow
} // namespace coroutines
} // namespace kotlinx
