/*
 * Copyright 2010-2024 JetBrains s.r.o. and Kotlin Programming Language contributors.
 * Use of this source code is governed by the Apache 2.0 license that can be found in the license/LICENSE.txt file.
 */
// port-lint: source compiler/ir/ir.tree/src/org/jetbrains/kotlin/ir/declarations/IrDeclarationBase.kt
// Transliterated from: compiler/ir/ir.tree/src/org/jetbrains/kotlin/ir/declarations/IrDeclarationBase.kt:11-28
#pragma once

#include "../IrElementBase.hpp"
#include "IrDeclaration.hpp"

namespace org::jetbrains::kotlin::ir::declarations {
/**
 * Unlike other [IrElement]s, this class is only an implementation detail, introduced
 * for convenience and performance.
 * As such, it is not autogenerated, but needs to be kept in sync with the entry in
 * tree generator: [org.jetbrains.kotlin.ir.generator.IrTree.declarationBase]
 */
// Transliterated from: compiler/ir/ir.tree/src/org/jetbrains/kotlin/ir/declarations/IrDeclarationBase.kt:17-28
class IrDeclarationBase : public IrElementBase, public virtual IrDeclaration {
 public:
  // Transliterated from: compiler/ir/ir.tree/src/org/jetbrains/kotlin/ir/declarations/IrDeclarationBase.kt:18-19
  IrDeclarationParent* parent_or_null() const;
  // Transliterated from: compiler/ir/ir.tree/src/org/jetbrains/kotlin/ir/declarations/IrDeclarationBase.kt:20-24
  IrDeclarationParent& parent() const override final;
  // Transliterated from: compiler/ir/ir.tree/src/org/jetbrains/kotlin/ir/declarations/IrDeclarationBase.kt:25-27
  void set_parent(IrDeclarationParent& value) override final;

 private:
  // NOTE(port): Borrow the exact compiler-owned parent, including its initial null.
  IrDeclarationParent* parent_ = nullptr;
};
}  // namespace org::jetbrains::kotlin::ir::declarations
