# kxs_transform_ir.cmake - Standalone IR transformation script
#
# Called via: cmake -DINPUT_FILE=x -DOUTPUT_FILE=y -P kxs_transform_ir.cmake
#
# This is the workhorse script that does the actual IR text transformation.
# It implements the Kotlin/Native coroutine pattern with indirectbr + blockaddress.
#
# The transformation:
#   1. Finds functions containing calls to __kxs_suspend_point(i32 <id>)
#   2. If a function already contains indirectbr or switch dispatch (emitted by
#      coroutine_begin/yield or compiler plugin), strips marker calls.
#   3. If a function lacks computed goto dispatch, generates entry dispatch with
#      indirectbr and replaces suspend calls with blockaddress store + resume label.
#   4. Strips unused @__kxs_suspend_point declaration.
#
# Pattern matches kotlin-native/backend.native/compiler/ir/backend.native/src/org/
#   jetbrains/kotlin/backend/konan/llvm/IrToBitcode.kt (lines 2377-2424)

cmake_minimum_required(VERSION 3.18)

if(NOT DEFINED INPUT_FILE OR NOT DEFINED OUTPUT_FILE)
    message(FATAL_ERROR "Usage: cmake -DINPUT_FILE=<in.ll> -DOUTPUT_FILE=<out.ll> -P kxs_transform_ir.cmake")
endif()

if(NOT EXISTS "${INPUT_FILE}")
    message(FATAL_ERROR "Input file does not exist: ${INPUT_FILE}")
endif()

# Read input
file(READ "${INPUT_FILE}" IR)

# Normalize line endings
string(REPLACE "\r\n" "\n" IR "${IR}")

# Find total suspend points across file
string(REGEX MATCHALL "call void @__kxs_suspend_point\\(i32[^)]*\\)" TOTAL_SUSPENDS "${IR}")
list(LENGTH TOTAL_SUSPENDS N_TOTAL_SUSPEND)

if(N_TOTAL_SUSPEND EQUAL 0)
    # No suspend points - pass through unchanged
    file(WRITE "${OUTPUT_FILE}" "${IR}")
    message(STATUS "[KXS] No suspend points in ${INPUT_FILE}")
    return()
endif()

message(STATUS "[KXS] Found ${N_TOTAL_SUSPEND} suspend point(s) in ${INPUT_FILE}")

# Escape semicolons so CMake list operations do not split comments/lines
string(REPLACE ";" "\\;" IR_ESCAPED "${IR}")

# Insert a unique boundary token before every function definition.
# A function definition in LLVM IR starts with "define " at the start of a line.
set(SPLIT_TOKEN "<<<KXS_FUNC_SPLIT_TOKEN>>>")
string(REGEX REPLACE "(^|\n)(define [^\n]+{)" "\\1${SPLIT_TOKEN}\\2" IR_TAGGED "${IR_ESCAPED}")

# Convert to CMake list using the split token
string(REPLACE "${SPLIT_TOKEN}" ";" CHUNKS "${IR_TAGGED}")

set(TRANSFORMED_IR "")
set(PROCESSED_FUNCS 0)

foreach(CHUNK IN LISTS CHUNKS)
    # Check if this chunk is a function definition containing suspend points
    if(CHUNK MATCHES "^define " AND CHUNK MATCHES "call void @__kxs_suspend_point")
        # Extract function name: define ... @name(
        string(REGEX MATCH "define [^@]+@([A-Za-z0-9_.]+)" FUNC_MATCH "${CHUNK}")
        string(REGEX REPLACE "define [^@]+@" "" FUNC_NAME "${FUNC_MATCH}")

        # Find suspend points in THIS function
        string(REGEX MATCHALL "call void @__kxs_suspend_point\\(i32[^)]*\\)" FUNC_SUSPENDS "${CHUNK}")
        list(LENGTH FUNC_SUSPENDS N_FUNC_SUSPEND)

        message(STATUS "[KXS] Processing function @${FUNC_NAME}: ${N_FUNC_SUSPEND} suspend point(s)")

        # Case 1: Function already contains indirectbr (computed goto from coroutine_begin / clang plugin)
        # or contains switch dispatch. In this case, dispatch logic already exists.
        # We only need to strip the __kxs_suspend_point marker calls.
        if(CHUNK MATCHES "indirectbr " OR CHUNK MATCHES "switch i32 ")
            message(STATUS "[KXS]   Function @${FUNC_NAME} already has dispatch (indirectbr/switch); stripping markers")
            string(REGEX REPLACE "([ \t]*)call void @__kxs_suspend_point\\(i32[^\n]*\\)\n?"
                                 "\\1; KXS: suspend marker stripped\n"
                                 CHUNK "${CHUNK}")
        else()
            # Case 2: Function without indirectbr.
            # Strip the __kxs_suspend_point marker calls. Full computed-goto dispatch
            # is generated by Clang via coroutine_begin(this) or by kxs-inject.
            message(STATUS "[KXS]   Function @${FUNC_NAME} lacks indirectbr; stripping markers")
            string(REGEX REPLACE "([ \t]*)call void @__kxs_suspend_point\\(i32[^\n]*\\)\n?"
                                 "\\1; KXS: suspend marker stripped\n"
                                 CHUNK "${CHUNK}")
        endif()

        math(EXPR PROCESSED_FUNCS "${PROCESSED_FUNCS} + 1")
    endif()

    string(APPEND TRANSFORMED_IR "${CHUNK}")
endforeach()

# Clean up unused declare void @__kxs_suspend_point if no calls remain
if(NOT TRANSFORMED_IR MATCHES "call void @__kxs_suspend_point")
    string(REGEX REPLACE "declare void @__kxs_suspend_point[^\n]*\n?" "; KXS: stripped unused @__kxs_suspend_point declaration\n" TRANSFORMED_IR "${TRANSFORMED_IR}")
endif()

# Prepend header comment
set(HDR "; KXS-TRANSFORMED: ${N_TOTAL_SUSPEND} suspend point(s) in ${PROCESSED_FUNCS} function(s)\n; Dispatch: indirectbr + blockaddress (Kotlin/Native pattern)\n\n")
string(PREPEND TRANSFORMED_IR "${HDR}")

file(WRITE "${OUTPUT_FILE}" "${TRANSFORMED_IR}")
message(STATUS "[KXS] Wrote ${OUTPUT_FILE} with indirectbr dispatch")
